### PR TITLE
Add capnproto addressbook example

### PR DESCRIPTION
**Pull request by dimakuv**
Add `capnproto` addressbook example.

Corresponding PR is https://github.com/oscarlab/graphene/pull/1333.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/73)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/73)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[capnproto/Makefile, line 44 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/73#-M12cNCHE8qQsDbXQVYq:-M12cNCHE8qQsDbXQVYr:b-1estxo) ([raw file](https://github.com/oscarlab/graphene-tests/blob/1dc21f8802826b3864c9c47c4a6b60c98c1d2295/capnproto/Makefile#L44)):*
> ```Makefile
> 		--sha256 $(ADDRESSBOOK_SRC_SHA256) --url $(ADDRESSBOOK_SRC_URL)
> 	$(GRAPHENEDIR)/Scripts/download --output $(SRCDIR)/addressbook.capnp \
> 		--sha256 $(ADDRESSBOOK_CAP_SHA256) --url $(ADDRESSBOOK_CAP_URL)
> ```

If this download fails, the next `make` call with think that this target is correctly built.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/73)* status: 3 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[capnproto/Makefile, line 44 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/73#-M12cNCHE8qQsDbXQVYq:-M133H6VD-KQwE5_O-HP:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/1dc21f8802826b3864c9c47c4a6b60c98c1d2295/capnproto/Makefile#L44)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

If this download fails, the next `make` call with think that this target is correctly built.
</blockquote></details>

Done.

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/73)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/73)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
