### PR TITLE
Improve TensorFlow README and Makefile

### PR DESCRIPTION
**Pull request by thomasknauth**
Improvements to README (automated search replace after deprecating SGX_RUN=1 screwed up the README) and Makefile.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/54)

### CODE REVIEW

**Comment by sudharkrish** [comment]
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/54#-LudkPoU-5f84Tvg8iDE:-LudkPoU-5f84Tvg8iDF:b-51jzf8) (no related file):*
Hi Thomas, this looks much better. If possible, it would be nice to structure the README as below, similar to README for other apps like apache, redis, nginx and so on. 

-build command(no SGX):
make

-build command(with SGX):
make SGX=1

-run original Tensorflow to analyse an image.

-run Tensorflow in non-SGX Graphene to analyse an image.

-run Tensorflow in Graphene-SGX to analyse an image.

---

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/54)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @thomasknauth)

___
*[tensorflow/Makefile, line 76 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/54#-LudsHTlBVXvY7S6u9hk:-LudsHTmEyGs9IqaJQLQ:b-36qlz) ([raw file](https://github.com/oscarlab/graphene-tests/blob/e743843304d31661f29667fd12e8a6feefc7f494/tensorflow/Makefile#L76)):*
> ```Makefile
> else
> check: default
> 	./label_image -m inception_v3.tflite -i image.bmp -t 1
> ```

Why is it the same as `run-native`? Shouldn't this target start TF under non-SGX Graphene?
___
*[tensorflow/README.md, line 10 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/54#-LudvH0LE6wyL1CdZ0Jr:-LudvH0M1B6KDKjxgf24:b8ts51m) ([raw file](https://github.com/oscarlab/graphene-tests/blob/e743843304d31661f29667fd12e8a6feefc7f494/tensorflow/README.md#L10)):*
> ```Markdown
> Install build dependencies with `make install-dependencies-ubuntu`.
> 
> Build everything with `make` (no SGX) or `SGX=1 make` (for SGX).
> ```

We use `make SGX=1` in all other places, please do the same for consistency (yup, seems we missed that in previous review, sorry).
___
*[tensorflow/README.md, line 12 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/54#-LudvZQ70kMZFWmJusW9:-LudvZQ87qHoEe6_ACnN:b-7ropln) ([raw file](https://github.com/oscarlab/graphene-tests/blob/e743843304d31661f29667fd12e8a6feefc7f494/tensorflow/README.md#L12)):*
> ```Markdown
> Build everything with `make` (no SGX) or `SGX=1 make` (for SGX).
> 
> `make run-native` labels a single image running native Tensorflow. `make run-graphene` executes the same program with Graphene. `SGX=1 make run-graphene` executes the label image program on Graphene with SGX.
> ```

ditto

**Review by thomasknauth — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/54)* status: 0 of 2 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow and @sudharkrish)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/54#-LudkPoU-5f84Tvg8iDE:-LuhvuiX6C70qQ_Z_5wZ:b-896fix) (no related file):*
<details><summary><i>Previously, sudharkrish (Sudha Krishnakumar) wrote…</i></summary><blockquote>

Hi Thomas, this looks much better. If possible, it would be nice to structure the README as below, similar to README for other apps like apache, redis, nginx and so on.

# build command(no SGX):
make

# build command(with SGX):
make SGX=1

# run original Tensorflow to analyse an image.

# run Tensorflow in non-SGX Graphene to analyse an image.

# run Tensorflow in Graphene-SGX to analyse an image.
</blockquote></details>

Done.

---
___
*[tensorflow/Makefile, line 76 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/54#-LudsHTlBVXvY7S6u9hk:-Luhwjmc3Rr8ucTZ350w:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/e743843304d31661f29667fd12e8a6feefc7f494/tensorflow/Makefile#L76)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why is it the same as `run-native`? Shouldn't this target start TF under non-SGX Graphene?
</blockquote></details>

Done.
___
*[tensorflow/README.md, line 10 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/54#-LudvH0LE6wyL1CdZ0Jr:-Luhwlof-N2w86sep4Z8:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/e743843304d31661f29667fd12e8a6feefc7f494/tensorflow/README.md#L10)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

We use `make SGX=1` in all other places, please do the same for consistency (yup, seems we missed that in previous review, sorry).
</blockquote></details>

Done.
___
*[tensorflow/README.md, line 12 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/54#-LudvZQ70kMZFWmJusW9:-LuhwmQPCDErawWx2F0V:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/e743843304d31661f29667fd12e8a6feefc7f494/tensorflow/README.md#L12)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Comment by sudharkrish** [comment]
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/54#-LuiE0ry2VG9eFxIf4fa:-LuiE0ry2VG9eFxIf4fb:b-9bke80) (no related file):*
It will be good, if we can add performance metrics(time taken for image analysis), in the 3 cases(vanilla, non-SGX Graphene, and Graphene-SGX).

---

**Comment by sudharkrish** [comment]
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/54#-LudkPoU-5f84Tvg8iDE:-LuiDGbY818UdAsEyQWO:b-b0k0f3) (no related file):*
<details><summary><i>Previously, thomasknauth (Thomas Knauth) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Personally, I would have preferred, a little more description like how the other README files have. Anyway, looks better now. 

---

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/54)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow, @sudharkrish, and @thomasknauth)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/54#-LudkPoU-5f84Tvg8iDE:-LuiGUCA65wTScqW5VKb:b-xj8ksh) (no related file):*
<details><summary><i>Previously, sudharkrish (Sudha Krishnakumar) wrote…</i></summary><blockquote>

Personally, I would have preferred, a little more description like how the other README files have. Anyway, looks better now. 
</blockquote></details>

@sudharkrish, please use backticks ("`") when citing code verbatim. Otherwise, GitHub/Reviewable format this text in unreadable junk.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/54#-LuiE0ry2VG9eFxIf4fa:-LuiGDUl0uKm-Ti37VKb:b-b6bpnr) (no related file):*
<details><summary><i>Previously, sudharkrish (Sudha Krishnakumar) wrote…</i></summary><blockquote>

It will be good, if we can add performance metrics(time taken for image analysis), in the 3 cases(vanilla, non-SGX Graphene, and Graphene-SGX).
</blockquote></details>

Why do we want performance metrics? These highly depend on the machine...

---
___
*[tensorflow/Makefile, line 76 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/54#-LudsHTlBVXvY7S6u9hk:-LuiHFRs5bjjBDYlF2zJ:bq52t2p) ([raw file](https://github.com/oscarlab/graphene-tests/blob/e743843304d31661f29667fd12e8a6feefc7f494/tensorflow/Makefile#L76)):*
<details><summary><i>Previously, thomasknauth (Thomas Knauth) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

But why this way? In all other examples, we use `pal_loader` instead of direct Graphene executables. This allows to ignore this hackery of `ifeq (SGX, 1)`. Also, using `pal_loader` is very handy when GDBing SGX apps. I'd prefer to go back to `pal_loader` way unless there is an important reason to *not* use it.
___
*[tensorflow/README.md, line 10 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/54#-LudvH0LE6wyL1CdZ0Jr:-LuiIGrr6KgJi3ZufQ7E:b-qoesns) ([raw file](https://github.com/oscarlab/graphene-tests/blob/e743843304d31661f29667fd12e8a6feefc7f494/tensorflow/README.md#L10)):*
<details><summary><i>Previously, thomasknauth (Thomas Knauth) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Can we replace `...` with `:`? This is a very unusual choice of punctuation.
___
*[tensorflow/README.md, line 12 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/54#-LudvZQ70kMZFWmJusW9:-LuiINil6WGpbDMBJVFf:b-qoesns) ([raw file](https://github.com/oscarlab/graphene-tests/blob/e743843304d31661f29667fd12e8a6feefc7f494/tensorflow/README.md#L12)):*
<details><summary><i>Previously, thomasknauth (Thomas Knauth) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Can we replace `...` with `:`? This is a very unusual choice of punctuation.
___
*[tensorflow/README.md, line 17 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/54#-LuiIPFx7bw_GPN5QXIf:-LuiIPFx7bw_GPN5QXIg:bbkkjjj) ([raw file](https://github.com/oscarlab/graphene-tests/blob/87f58e67f5467dc7c0852f38f98a93a705308883/tensorflow/README.md#L17)):*
> ```Markdown
> - do `make run-native`
> - on Graphene do `make run-graphene`
> - on Graphene with SGX do `make SGX=1 run-graphene`
> ```

Could you change text similar to above? E.g.
```
- without Graphene do `make run-native`
- with Graphene do ...
- with Graphene with SGX do ...
```

Are we departing from `Graphene-SGX`? I think it's more meaningful than `Graphene with SGX`.

**Comment by sudharkrish** [comment]
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/54#-LuiE0ry2VG9eFxIf4fa:-LuiXbqY4bcz3IKuU-pD:bog0f0c) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do we want performance metrics? These highly depend on the machine...
</blockquote></details>

Adding benchmarks(or metrics), is similar to what we have today for apache, redis, nginx and other apps. Numbers will differ on the type of platform, but user running is going to get better numbers based on their platform and that is a given. But we will get an idea of how much it differs relative to the use-case(vanilla, non-SGX Graphene, Graphene-SGX).

---

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/54)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow, @sudharkrish, and @thomasknauth)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/54#-LuiE0ry2VG9eFxIf4fa:-LuirKgG6wGM3qDQjRkP:b-8ss21k) (no related file):*
<details><summary><i>Previously, sudharkrish (Sudha Krishnakumar) wrote…</i></summary><blockquote>

Adding benchmarks(or metrics), is similar to what we have today for apache, redis, nginx and other apps. Numbers will differ on the type of platform, but user running is going to get better numbers based on their platform and that is a given. But we will get an idea of how much it differs relative to the use-case(vanilla, non-SGX Graphene, Graphene-SGX).
</blockquote></details>

What do you mean by `we have today for apache, redis, nginx and other apps`? We don't have any perf numbers in those examples.

---

**Review by thomasknauth — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/54)* status: 0 of 2 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @mkow, and @sudha)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/54#-LuiE0ry2VG9eFxIf4fa:-Luin0nh2eEUFcpEf2Pj:b8a468v) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What do you mean by `we have today for apache, redis, nginx and other apps`? We don't have any perf numbers in those examples.
</blockquote></details>

I think what Sudha would like to have is a benchmark script for simple performance evaluation. I agree, nice to have, but I am not inclined to invest more time into this. @Sudha, you are blocking on this. Please mark this as resolved even though there is no such benchmark script today. Thanks. Next time, you should mark this as a comment, instead of blocking on it.

---
___
*[tensorflow/Makefile, line 76 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/54#-LudsHTlBVXvY7S6u9hk:-LuinFCy8ECKUJiyPZIw:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/e743843304d31661f29667fd12e8a6feefc7f494/tensorflow/Makefile#L76)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But why this way? In all other examples, we use `pal_loader` instead of direct Graphene executables. This allows to ignore this hackery of `ifeq (SGX, 1)`. Also, using `pal_loader` is very handy when GDBing SGX apps. I'd prefer to go back to `pal_loader` way unless there is an important reason to *not* use it.
</blockquote></details>

Done.
___
*[tensorflow/README.md, line 17 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/54#-LuiIPFx7bw_GPN5QXIf:-LuimtdT4oHEZnxDk4mq:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/87f58e67f5467dc7c0852f38f98a93a705308883/tensorflow/README.md#L17)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you change text similar to above? E.g.
```
- without Graphene do `make run-native`
- with Graphene do ...
- with Graphene with SGX do ...
```

Are we departing from `Graphene-SGX`? I think it's more meaningful than `Graphene with SGX`.
</blockquote></details>

Done.

**Review by dimakuv — DISMISSED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/54)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow and @sudha)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/54#-LuiE0ry2VG9eFxIf4fa:-Luiw0f6-bUzy4yRyec6:brkvjb0) (no related file):*
<details><summary><i>Previously, thomasknauth (Thomas Knauth) wrote…</i></summary><blockquote>

I think what Sudha would like to have is a benchmark script for simple performance evaluation. I agree, nice to have, but I am not inclined to invest more time into this. @Sudha, you are blocking on this. Please mark this as resolved even though there is no such benchmark script today. Thanks. Next time, you should mark this as a comment, instead of blocking on it.
</blockquote></details>

Got it, thanks for explanation. Sudha, sorry for confusion.

---

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/54)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by mkow — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/54)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @thomasknauth)

___
*[tensorflow/README.md, line 1 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/54#-LujR60W99SawNfemKAY:-LujR60W99SawNfemKAZ:b8xqxr6) ([raw file](https://github.com/oscarlab/graphene-tests/blob/bc75f7e63632b02312e70eb4de50d1525f66cc00/tensorflow/README.md#L1)):*
> ```Markdown
> This example demonstrates how to run Tensorflow (v1.9) Lite's label_image example on Graphene. Reads an input image `image.bmp` from the current directory and uses Tensorflow lite and the Inception v3 model to label the image.
> ```

Actually, the correct casing is `TensorFlow`, not `Tensorflow`. Could you fix it in this readme while we are here?

**Review by thomasknauth — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/54)* status: 1 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @mkow)

___
*[tensorflow/README.md, line 1 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/54#-LujR60W99SawNfemKAY:-Lv6ecUD4ledW7xqMxIp:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/bc75f7e63632b02312e70eb4de50d1525f66cc00/tensorflow/README.md#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Actually, the correct casing is `TensorFlow`, not `Tensorflow`. Could you fix it in this readme while we are here?
</blockquote></details>

Done.

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/54)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/54)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/54)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/54)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
