### PR TITLE
Rewrite busybox example

### PR DESCRIPTION
**Pull request by boryspoplawski**
There are still some issues, main is that graphene currently doesn't handle '/proc/self/exe' well, but it is used by busybox to spawn subprograms (it reexecutes itself with different argv[0]).
Not sure if that is a blocker, since fix won't touch this repository

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/30)

### CODE REVIEW

**Review by yamahata — COMMENTED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/30)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski)

___
*[busybox/Makefile, line 5 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/30#-Ln0s69qEqgBPzRcIWFU:-Ln0rxP41BwiBoA_SF4A:bb8x66k) ([raw file](https://github.com/oscarlab/graphene-tests/blob/35d76947e245d1a3b08c5c29eea51c0dd6497f1f/busybox/Makefile#L5)):*
> ```Makefile
> 
> level = ../../
> include ../../Makefile
> ```

is there any reason to drop this?
It defines PALDIR, SHIMDIR and RUNTIME.
___
*[busybox/Makefile, line 74 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/30#-Ln0sVQb9bNgK2m4HFUb:-Ln0sVQb9bNgK2m4HFUc:b-bq5kw) ([raw file](https://github.com/oscarlab/graphene-tests/blob/bfc4771f56f6454be94c58a19660612275c697f1/busybox/Makefile#L74)):*
> ```Makefile
> # name (i.e., "busybox").
> 
> busybox.manifest.sgx: busybox.manifest $(SRCDIR)/busybox
> ```

Please check https://github.com/oscarlab/graphene/pull/945

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/30)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @yamahata)

___
*[busybox/default.config, line 2 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/30#-Ln7mYAVDF0cbYOLYlTY:-Ln7mYAVDF0cbYOLYlTZ:bilvg75) ([raw file](https://github.com/oscarlab/graphene-tests/blob/bfc4771f56f6454be94c58a19660612275c697f1/busybox/default.config#L2)):*
> ```
> #
> # Automatically generated make config: don't edit
> ```

How was it generated? Could we include generating it as part of the build process? It's hard to see what entries we modified (against the defaults) in this version.
___
*[busybox/Makefile, line 5 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/30#-Ln0s69qEqgBPzRcIWFU:-Ln7rCiv4gR8u5eS9Zob:b-og0qr4) ([raw file](https://github.com/oscarlab/graphene-tests/blob/35d76947e245d1a3b08c5c29eea51c0dd6497f1f/busybox/Makefile#L5)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

is there any reason to drop this?
It defines PALDIR, SHIMDIR and RUNTIME.

</blockquote></details>

I think we decided to have those Makefiles as independent of Graphene build system as possible (especially if it's not needed).

**Review by yamahata — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/30)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)

**Review by thomasknauth — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/30)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)

___
*[busybox/Makefile, line 45 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/30#-LnYo5qqAFrtwhCGwQ_m:-LnYo5qqAFrtwhCGwQ_n:bw3e3ro) ([raw file](https://github.com/oscarlab/graphene-tests/blob/bfc4771f56f6454be94c58a19660612275c697f1/busybox/Makefile#L45)):*
> ```Makefile
> 
> $(SRCDIR)/.config:
> 	git clone git://busybox.net/busybox.git $(SRCDIR)
> ```

Can we switch to https://git.busybox.net/busybox/ instead of git://? That would make people behind corporate firewalls/proxies happier? Even better, just grab the tar-ball. For some reason, git clone takes forever (2 minutes!).
___
*[busybox/README.md, line 22 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/30#-LnYsLFB1ny9nB1O3Oe9:-LnYsLFB1ny9nB1O3OeA:b-c145b3) ([raw file](https://github.com/oscarlab/graphene-tests/blob/bfc4771f56f6454be94c58a19660612275c697f1/busybox/README.md#L22)):*
> ```Markdown
> # run Busybox shell in Graphene-SGX
> SGX=1 ./pal_loader busybox sh
> ```
> ```

Possibly include a command or two for the user to run to see that it actually does something; for people like me, who don't "breath" busybox. For me the prompt didn't even change or sth. At least mention they can type help to get started.

**Review by boryspoplawski — COMMENTED** [review]
Fixed previous issues, but now depends on PR #971 from the main graphene repository.
Removed hardcoded config, now build process auto-generates one.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/30#-:-LnrodtRAEhoa96swcoJ:bhivkna)* status: 6 of 9 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @mkow, @thomasknauth, and @yamahata)

___
*[busybox/default.config, line 2 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/30#-Ln7mYAVDF0cbYOLYlTY:-Lnronii3orPzYWwEOdl:buu0wn5) ([raw file](https://github.com/oscarlab/graphene-tests/blob/bfc4771f56f6454be94c58a19660612275c697f1/busybox/default.config#L2)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

How was it generated? Could we include generating it as part of the build process? It's hard to see what entries we modified (against the defaults) in this version.
</blockquote></details>

No longed applies
___
*[busybox/Makefile, line 5 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/30#-Ln0s69qEqgBPzRcIWFU:-LnrpuvT7yuo-SHQYQ5d:bsfu9n8) ([raw file](https://github.com/oscarlab/graphene-tests/blob/35d76947e245d1a3b08c5c29eea51c0dd6497f1f/busybox/Makefile#L5)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think we decided to have those Makefiles as independent of Graphene build system as possible (especially if it's not needed).
</blockquote></details>

Only things that are needed here are: path to runtime directory and path to directory with utilities for SGX signing. Including whole makefile seems like an overkill.
___
*[busybox/Makefile, line 45 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/30#-LnYo5qqAFrtwhCGwQ_m:-LnrqaAqEQM2P2ORolGW:baaz4mi) ([raw file](https://github.com/oscarlab/graphene-tests/blob/bfc4771f56f6454be94c58a19660612275c697f1/busybox/Makefile#L45)):*
<details><summary><i>Previously, thomasknauth (Thomas Knauth) wrote…</i></summary><blockquote>

Can we switch to https://git.busybox.net/busybox/ instead of git://? That would make people behind corporate firewalls/proxies happier? Even better, just grab the tar-ball. For some reason, git clone takes forever (2 minutes!).
</blockquote></details>

`https://git.busybox.net/busybox/` doesn't seem to work (couldn't clone it).
Weird, for me cloning this takes 15s (on a not the best hardware, but with a decent  internet connection).

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/30)* status: 6 of 9 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @mkow, @thomasknauth, and @yamahata)

___
*[busybox/README.md, line 22 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/30#-LnYsLFB1ny9nB1O3Oe9:-Lnrx4Pi0-O4KFNdE2LY:b-v0zlq7) ([raw file](https://github.com/oscarlab/graphene-tests/blob/bfc4771f56f6454be94c58a19660612275c697f1/busybox/README.md#L22)):*
<details><summary><i>Previously, thomasknauth (Thomas Knauth) wrote…</i></summary><blockquote>

Possibly include a command or two for the user to run to see that it actually does something; for people like me, who don't "breath" busybox. For me the prompt didn't even change or sth. At least mention they can type help to get started.
</blockquote></details>

Added an example.
Couldn't add a prompt since graphene does not support tty handling, so this is not an interactive session

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/30)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @mkow, @thomasknauth, and @yamahata)

___
*[busybox/busybox.manifest.template, line 136 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/30#-Lo1Xpz-1Yjhj0MI94sE:-Lo1Xpz0CUhnpEcEJVQ3:bs73c1j) ([raw file](https://github.com/oscarlab/graphene-tests/blob/96b4fc7435141d0c846867b02a09b2dbe4fb82ca/busybox/busybox.manifest.template#L136)):*
> ```
> sgx.allowed_files.passwd    = file:/etc/passwd
> 
> sgx.allowed_files.localtime = file:/etc/localtime
> ```

Could you add an explanation for localtime? Why is it required for Busybox? Or at least that this is a "timezone data" file explicitly accessed by Busybox.
___
*[busybox/Makefile, line 45 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/30#-LnYo5qqAFrtwhCGwQ_m:-Lo1Z-gnCBjLqzptB9y6:b57lbqg) ([raw file](https://github.com/oscarlab/graphene-tests/blob/bfc4771f56f6454be94c58a19660612275c697f1/busybox/Makefile#L45)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`https://git.busybox.net/busybox/` doesn't seem to work (couldn't clone it).
Weird, for me cloning this takes 15s (on a not the best hardware, but with a decent  internet connection).
</blockquote></details>

`git clone https://github.com/mirror/busybox.git` works perfectly fine. I second Thomas, please use this HTTPS link (GIT protocol is disallowed in our corporate firewall).
___
*[busybox/Makefile, line 74 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/30#-Ln0sVQb9bNgK2m4HFUb:-Lo1_6io5I3xduz6H1Z0:bmwoyfa) ([raw file](https://github.com/oscarlab/graphene-tests/blob/bfc4771f56f6454be94c58a19660612275c697f1/busybox/Makefile#L74)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

Please check https://github.com/oscarlab/graphene/pull/945
</blockquote></details>

I'd keep as-is for now, without making a dependency on 945. We can update all makefiles in a separate PR after 945 is merged.
___
*[busybox/Makefile, line 9 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/30#-Lo1YUak-6HYcK7ZlPnx:-Lo1YUal6UE4ltAt8LB4:b-z1f0t) ([raw file](https://github.com/oscarlab/graphene-tests/blob/96b4fc7435141d0c846867b02a09b2dbe4fb82ca/busybox/Makefile#L9)):*
> ```Makefile
> #
> # Any of these invocations clones busybox git repository and builds it
> # in the configuration according to default.config, in the latest (master
> ```

What is `default.config`? Looks like an artifact of the previous version of this PR.
___
*[busybox/Makefile, line 40 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/30#-Lo1YoikAwjWnRqxzMH8:-Lo1YoikAwjWnRqxzMH9:b5t7mac) ([raw file](https://github.com/oscarlab/graphene-tests/blob/96b4fc7435141d0c846867b02a09b2dbe4fb82ca/busybox/Makefile#L40)):*
> ```Makefile
> # Busybox is built as usual, without any changes to the build process. The
> # source is cloned from a public repo and built via classic make, using
> # predefined config file ".config" (just for convenience). The result of this
> ```

What is `.config`? Looks like an artifact of the previous version of this PR.
___
*[busybox/Makefile, line 50 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/30#-Lo1ZhGaEW9idxlaYi1H:-Lo1ZhGaEW9idxlaYi1I:b-hpohza) ([raw file](https://github.com/oscarlab/graphene-tests/blob/96b4fc7435141d0c846867b02a09b2dbe4fb82ca/busybox/Makefile#L50)):*
> ```Makefile
> 	cd $(SRCDIR) && make clean && make defconfig
> 	sed -e 's/.*CONFIG_BUSYBOX_EXEC_PATH.*/CONFIG_BUSYBOX_EXEC_PATH="\/busybox"/' -i $(SRCDIR)/.config
> 	sed -e 's/.*CONFIG_FEATURE_SH_STANDALONE.*/CONFIG_FEATURE_SH_STANDALONE=y/' -i $(SRCDIR)/.config
> ```

For these two config options, could you explain why they are needed (in a comment)?

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/30)* status: 7 of 9 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @mkow, and @thomasknauth)

___
*[busybox/busybox.manifest.template, line 136 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/30#-Lo1Xpz-1Yjhj0MI94sE:-Lo3K4dyAJhjGNko8Y9i:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/96b4fc7435141d0c846867b02a09b2dbe4fb82ca/busybox/busybox.manifest.template#L136)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you add an explanation for localtime? Why is it required for Busybox? Or at least that this is a "timezone data" file explicitly accessed by Busybox.
</blockquote></details>

Done.
___
*[busybox/Makefile, line 45 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/30#-LnYo5qqAFrtwhCGwQ_m:-Lo3KAF34rssCqzqbWoa:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/bfc4771f56f6454be94c58a19660612275c697f1/busybox/Makefile#L45)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`git clone https://github.com/mirror/busybox.git` works perfectly fine. I second Thomas, please use this HTTPS link (GIT protocol is disallowed in our corporate firewall).
</blockquote></details>

Done.
___
*[busybox/Makefile, line 9 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/30#-Lo1YUak-6HYcK7ZlPnx:-Lo3K8EbBn4OGzFW8LwV:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/96b4fc7435141d0c846867b02a09b2dbe4fb82ca/busybox/Makefile#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is `default.config`? Looks like an artifact of the previous version of this PR.
</blockquote></details>

Done.
___
*[busybox/Makefile, line 40 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/30#-Lo1YoikAwjWnRqxzMH8:-Lo3K9E9EgC7uI1XNmdL:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/96b4fc7435141d0c846867b02a09b2dbe4fb82ca/busybox/Makefile#L40)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is `.config`? Looks like an artifact of the previous version of this PR.
</blockquote></details>

Done.
___
*[busybox/Makefile, line 50 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/30#-Lo1ZhGaEW9idxlaYi1H:-Lo3KCUN4NnjZZXnCXDN:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/96b4fc7435141d0c846867b02a09b2dbe4fb82ca/busybox/Makefile#L50)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

For these two config options, could you explain why they are needed (in a comment)?
</blockquote></details>

Done.

**Review by dimakuv — DISMISSED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/30)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow and @thomasknauth)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/30)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @thomasknauth)

___
*[busybox/busybox.manifest.template, line 137 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/30#-Lo7FOGk7TME4pDDLuld:-Lo7FOGk7TME4pDDLule:bwtyvlv) ([raw file](https://github.com/oscarlab/graphene-tests/blob/01b0d235f2c35e60fcf20db5438a87b4aeb0a236/busybox/busybox.manifest.template#L137)):*
> ```
> 
> # Busybox uses timezone settings, which are located in /etc/localtime for glibc
> # based host systems.
> ```

`glibc based` -> `glibc-based`

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/30)* status: 8 of 9 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @mkow, and @thomasknauth)

___
*[busybox/busybox.manifest.template, line 137 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/30#-Lo7FOGk7TME4pDDLuld:-Lo7xW7I7z9ie4w72HOf:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/01b0d235f2c35e60fcf20db5438a87b4aeb0a236/busybox/busybox.manifest.template#L137)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`glibc based` -> `glibc-based`
</blockquote></details>

Done.

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/30)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @thomasknauth)

**Review by dimakuv — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/30)* status: all files reviewed, 2 unresolved discussions (waiting on @thomasknauth)

**Comment by dimakuv** [comment]
@boryspoplawski Can you create a corresponding PR in the main graphene repo? This one is almost ready for merge.

**Review by boryspoplawski — COMMENTED** [review]
Done. https://github.com/oscarlab/graphene/pull/982

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/30#-:-LoLOeJb776yGZ4EoFpA:b5tfu09)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/30)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/30)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
