### PR TITLE
Add work-in-progress disclaimers to unfinished integrations

### PR DESCRIPTION
**Pull request by mkow**
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/41)

### CODE REVIEW

**Review by omeg — DISMISSED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/41)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/41)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[lighttpd/README, line 2 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/41#-LoVrqUOEzP4JKVgIkDq:-LoVrqUOEzP4JKVgIkDr:b3ktnmn) ([raw file](https://github.com/oscarlab/graphene-tests/blob/a6772c2f522a1b7459eae3ea105125e13e335221/lighttpd/README#L2)):*
> ```
> This sample integration is being reworked and will soon be updated. If you are interested in the
> details, you can take a look at the relevant PR: https://github.com/oscarlab/graphene-tests/pull/37.
> ```

`<https://...>`?
___
*[ltp/README, line 5 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/41#-LoVs1Qc-G2YpsxL36Bf:-LoVs1Qc-G2YpsxL36Bg:b3ktnmn) ([raw file](https://github.com/oscarlab/graphene-tests/blob/a6772c2f522a1b7459eae3ea105125e13e335221/ltp/README#L5)):*
> ```
> 
> This test suite integration is being reworked and will soon be updated. If you are interested in the
> details, you can take a look at the relevant PR: https://github.com/oscarlab/graphene-tests/pull/21.
> ```

`<https://...>`?

**Review by dimakuv — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/41)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/41)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by omeg — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/41)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/41)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

___
*[lighttpd/README, line 2 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/41#-LoVrqUOEzP4JKVgIkDq:-LoVttuwC3rpaJCkwCDL:b-a0pn6g) ([raw file](https://github.com/oscarlab/graphene-tests/blob/a6772c2f522a1b7459eae3ea105125e13e335221/lighttpd/README#L2)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`<https://...>`?
</blockquote></details>

This file seems to not be written in Markdown
___
*[ltp/README, line 5 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/41#-LoVs1Qc-G2YpsxL36Bf:-LoVtzMj19b1EoSnapGi:b-a0pn6g) ([raw file](https://github.com/oscarlab/graphene-tests/blob/a6772c2f522a1b7459eae3ea105125e13e335221/ltp/README#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`<https://...>`?
</blockquote></details>

This file seems to not be written in Markdown

**Pull request merged**
