### PR TITLE
Use download script

### PR DESCRIPTION
**Pull request by HW42**
This also pins all downloads to a specific version instead of using
master sometimes. Otherwise it's unclear if the used configuration was
ever tested at all.

Matching PR: https://github.com/oscarlab/graphene/pull/1291.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/70)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/70)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @HW42)

___
*[busybox/.gitignore, line 3 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/70#-LzxdyY_BwDoFqC_XHdU:-LzxdyY_BwDoFqC_XHdV:bky3es9) ([raw file](https://github.com/oscarlab/graphene-tests/blob/9e34f3158ff45c31353edf2d9616a8085a4f7a01/busybox/.gitignore#L3)):*
> ```ignore
> src/
> busybox
> busybox.tar.bz2
> ```

Should be `/busybox.tar.bz2`. I think it's the same for other entries which were already here.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/70)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @HW42)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/70#-LzyDwaHDH--uNUplPjB:-LzyDwaHDH--uNUplPjC:bi1epjf) (no related file):*
Minor, but did you test that builds still work?

---
___
*[memcached/Makefile, line 37 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/70#-LzyDJF58vIIGAJFg1vn:-LzyDJF58vIIGAJFg1vo:bqws9ej) ([raw file](https://github.com/oscarlab/graphene-tests/blob/9e34f3158ff45c31353edf2d9616a8085a4f7a01/memcached/Makefile#L37)):*
> ```Makefile
> 
> # Memcached is built as usual, without any changes to the build process. The
> # source is downloaded from GitHub and built via classic ./autogen.sh &&
> ```

It is downloaded not from GitHub but from memcached.org now.

**Review by HW42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/70)* status: 10 of 12 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/70#-LzyDwaHDH--uNUplPjB:-M-AJjmg7_QL3vGlPs0O:bdzjj5i) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Minor, but did you test that builds still work?
</blockquote></details>

IIRC: I tested all builds on the 'Linux'-host except tensorflow. For those that didn't had a included test target I didn't do anything beyond checking that the built binary didn't crashed immediately. For tensorflow I only checked the download so far since it tries to install bazel globally which I didn't want in my normal test env. Will check it later today.

---
___
*[busybox/.gitignore, line 3 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/70#-LzxdyY_BwDoFqC_XHdU:-M-AL1Kc-g0sYb-25PWV:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/9e34f3158ff45c31353edf2d9616a8085a4f7a01/busybox/.gitignore#L3)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Should be `/busybox.tar.bz2`. I think it's the same for other entries which were already here.
</blockquote></details>

Done.
___
*[memcached/Makefile, line 37 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/70#-LzyDJF58vIIGAJFg1vn:-M-ALeU10_RQkvi-OKEy:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/9e34f3158ff45c31353edf2d9616a8085a4f7a01/memcached/Makefile#L37)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

It is downloaded not from GitHub but from memcached.org now.
</blockquote></details>

Done.

**Review by HW42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/70)* status: 10 of 12 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/70#-LzyDwaHDH--uNUplPjB:-M-Axt73DIBC4nksyuq3:b-joc7ca) (no related file):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

IIRC: I tested all builds on the 'Linux'-host except tensorflow. For those that didn't had a included test target I didn't do anything beyond checking that the built binary didn't crashed immediately. For tensorflow I only checked the download so far since it tries to install bazel globally which I didn't want in my normal test env. Will check it later today.
</blockquote></details>

Just tested: tensorflow also still builds and `run-graphene` works.

---

**Review by dimakuv — DISMISSED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/70)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)

**Review by yamahata — DISMISSED** [review]
> Reviewed 10 of 12 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/70)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @mkow)

**Review by mkow — DISMISSED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/70)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/70)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/70)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
