### PR TITLE
Introduce two variables to benchmark-http.sh

### PR DESCRIPTION
**Pull request by chiache**
This PR allows users to tune the test iterations in benchmark-http.sh, with two variabls:
- `LOOP`: the iterations for repeating the `ab` command (default: 1)
- `CONCURRENCY_LIST`: configurations of the concurrency level for the `ab` command (default: `1 2 4 8 16 32 64 128 256`

For example:
```
LOOP=1 CONCURRENCY_LIST="1 32" ./benchmark-http.sh 172.17.0.1:8000
```

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/15)

### CODE REVIEW

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/15)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by donporter — DISMISSED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/15)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/15)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/15)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/15)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
