### PR TITLE
Drop usage SGX_RUN

### PR DESCRIPTION
**Pull request by HW42**
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/35)

### CODE REVIEW

**Review by dimakuv — DISMISSED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/35)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by yamahata — DISMISSED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/35)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/35)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/35)* status: all files reviewed, 1 unresolved discussion (waiting on @HW42)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/35#-Lp5wu6_1LKTwjw8kGp5:-Lp5wu6_1LKTwjw8kGp6:baamht7) (no related file):*
@hw42 In the meantime we migrated our GitHub Wiki to the repo (Documentation/oldwiki; http://graphene.readthedocs.io/), could you also update it?

---

**Review by dimakuv — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/35)* status: all files reviewed, 1 unresolved discussion (waiting on @HW42)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/35#-Lp5wu6_1LKTwjw8kGp5:-LpV5GJ922STwKhYefoC:b-x0q79h) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@hw42 In the meantime we migrated our GitHub Wiki to the repo (Documentation/oldwiki; http://graphene.readthedocs.io/), could you also update it?
</blockquote></details>

@mkow, shouldn't you move this comment to the corresponding PR in the main *graphene* repo?

---

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/35)* status: :shipit: complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/35#-Lp5wu6_1LKTwjw8kGp5:-Lp_xq0SDfppZk1mRsGZ:b-evt3t0) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@mkow, shouldn't you move this comment to the corresponding PR in the main *graphene* repo?
</blockquote></details>

oh, sorry, my bad. fixed.

---

**Review by mkow — DISMISSED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/35)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dimakuv — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/35)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/35)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/35)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
