### PR TITLE
Add a README.md

### PR DESCRIPTION
**Pull request by chiache**
Adding a top-level README.md for the graphene-tests repository.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/34)

### CODE REVIEW

**Review by thomasknauth — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/34)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache)

___
*[README.md, line 8 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/34#-LnTfT1b5RwvGz0kyEc8:-LnTfT1b5RwvGz0kyEc9:b-9370lh) ([raw file](https://github.com/oscarlab/graphene-tests/blob/2b3fd48e725c5a8dccac4e505d2f78bd319d330a/README.md#L8)):*
> ```Markdown
> please see the README in the Graphene repository.
> 
> For the instructions to build and run each application under
> ```

For the instructions -> For instructions
___
*[README.md, line 30 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/34#-LnTejJDDzVXEdATZpfS:-LnTejJDDzVXEdATZpfT:b-ffg19c) ([raw file](https://github.com/oscarlab/graphene-tests/blob/2b3fd48e725c5a8dccac4e505d2f78bd319d330a/README.md#L30)):*
> ```Markdown
>   Users should be able to build your application sample by running
>   the `make` command. If your application needs extra building steps,
>   please document them in the `README.md`. In addition. we ask you
> ```

In addition. -> In addition,
___
*[README.md, line 32 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/34#-LnTeqZMCWmIYSVE9x-q:-LnTeqZMCWmIYSVE9x-r:b-gctcd9) ([raw file](https://github.com/oscarlab/graphene-tests/blob/2b3fd48e725c5a8dccac4e505d2f78bd319d330a/README.md#L32)):*
> ```Markdown
>   please document them in the `README.md`. In addition. we ask you
>   to provide sufficient comments in the `Makefile` to help users
>   understand the building process. If your application also run in
> ```

building -> build; run in -> runs on
___
*[README.md, line 51 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/34#-LnTfA9_6rvnNoxdhPT0:-LnTfA9_6rvnNoxdhPT1:b-q9tu8s) ([raw file](https://github.com/oscarlab/graphene-tests/blob/2b3fd48e725c5a8dccac4e505d2f78bd319d330a/README.md#L51)):*
> ```Markdown
> Please do not include any tarball of source code or binaries in the
> application samples. If an application requires downloading the source
> code or binaries, please provide the instruction in the `README.md`.
> ```

please provide instructions in the README.md or, even better, gather them automatically as part of the makefile/build process.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/34)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache)

___
*[README.md, line 22 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/34#-LnpzJc6-vLVy-WAdP9f:-LnpzJc6-vLVy-WAdP9g:b-hqfym2) ([raw file](https://github.com/oscarlab/graphene-tests/blob/2b3fd48e725c5a8dccac4e505d2f78bd319d330a/README.md#L22)):*
> ```Markdown
> 
> - `README.md`:
>   Please document the tested environment and the instruction for
> ```

`the instruction` -> `instructions`

**Review by chiache — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/34)* status: 0 of 1 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @dimakuv and @thomasknauth)

___
*[README.md, line 8 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/34#-LnTfT1b5RwvGz0kyEc8:-LnrmBi40yhP0-EWMydO:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/2b3fd48e725c5a8dccac4e505d2f78bd319d330a/README.md#L8)):*
<details><summary><i>Previously, thomasknauth (Thomas Knauth) wrote…</i></summary><blockquote>

For the instructions -> For instructions
</blockquote></details>

Done.
___
*[README.md, line 22 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/34#-LnpzJc6-vLVy-WAdP9f:-LnrmIBnEC8gog6mR6b9:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/2b3fd48e725c5a8dccac4e505d2f78bd319d330a/README.md#L22)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`the instruction` -> `instructions`
</blockquote></details>

Done.
___
*[README.md, line 30 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/34#-LnTejJDDzVXEdATZpfS:-LnrmMqe7RFi0aFNjH3Z:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/2b3fd48e725c5a8dccac4e505d2f78bd319d330a/README.md#L30)):*
<details><summary><i>Previously, thomasknauth (Thomas Knauth) wrote…</i></summary><blockquote>

In addition. -> In addition,
</blockquote></details>

Done.
___
*[README.md, line 32 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/34#-LnTeqZMCWmIYSVE9x-q:-LnrmVaTAlOacV5Yd1ll:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/2b3fd48e725c5a8dccac4e505d2f78bd319d330a/README.md#L32)):*
<details><summary><i>Previously, thomasknauth (Thomas Knauth) wrote…</i></summary><blockquote>

building -> build; run in -> runs on
</blockquote></details>

Done.
___
*[README.md, line 51 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/34#-LnTfA9_6rvnNoxdhPT0:-Lnrn0kW2WsYr0YSq7-o:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/2b3fd48e725c5a8dccac4e505d2f78bd319d330a/README.md#L51)):*
<details><summary><i>Previously, thomasknauth (Thomas Knauth) wrote…</i></summary><blockquote>

please provide instructions in the README.md or, even better, gather them automatically as part of the makefile/build process.
</blockquote></details>

Done.

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/34)* status: all files reviewed, 4 unresolved discussions (waiting on @thomasknauth)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/34)* status: all files reviewed, 7 unresolved discussions (waiting on @chiache and @thomasknauth)

___
*[README.md, line 8 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/34#-LoKv79s1VIyew0_wETO:-LoKv79s1VIyew0_wETP:b-yy88fu) ([raw file](https://github.com/oscarlab/graphene-tests/blob/81af416c673be19c56a7e83fe2969bd52e16c3fb/README.md#L8)):*
> ```Markdown
> please see the README in the Graphene repository.
> 
> For instructions to build and run each application under Graphene,
> ```

`For instructions to build` -> `For instructions how to build`
___
*[README.md, line 24 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/34#-LoKvOBY-x-L6w8mxLCa:-LoKvOBZ4gps4yaoBjmn:b-2xdh34) ([raw file](https://github.com/oscarlab/graphene-tests/blob/81af416c673be19c56a7e83fe2969bd52e16c3fb/README.md#L24)):*
> ```Markdown
>   Please document the tested environment and instructions for
>   building and running the application. If your application sample
>   has any known issue or requirement, please also specify in the
> ```

`issue or requirement` -> `issues or requirements`
___
*[README.md, line 24 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/34#-LoKvR4KEANxOKjqNMOY:-LoKvR4KEANxOKjqNMOZ:b-e4awxg) ([raw file](https://github.com/oscarlab/graphene-tests/blob/81af416c673be19c56a7e83fe2969bd52e16c3fb/README.md#L24)):*
> ```Markdown
>   Please document the tested environment and instructions for
>   building and running the application. If your application sample
>   has any known issue or requirement, please also specify in the
> ```

`please also specify in the` -> `please also specify them in the`

**Review by chiache — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/34)* status: 0 of 1 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @dimakuv and @mkow)

___
*[README.md, line 8 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/34#-LoKv79s1VIyew0_wETO:-LoREAq6CPbPwDH5Ywjk:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/81af416c673be19c56a7e83fe2969bd52e16c3fb/README.md#L8)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`For instructions to build` -> `For instructions how to build`
</blockquote></details>

Done.
___
*[README.md, line 24 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/34#-LoKvOBY-x-L6w8mxLCa:-LoREBd07dB8gSju4jEP:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/81af416c673be19c56a7e83fe2969bd52e16c3fb/README.md#L24)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`issue or requirement` -> `issues or requirements`
</blockquote></details>

Done.
___
*[README.md, line 24 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/34#-LoKvR4KEANxOKjqNMOY:-LoRECcBEFNQslD5ktDA:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/81af416c673be19c56a7e83fe2969bd52e16c3fb/README.md#L24)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`please also specify in the` -> `please also specify them in the`
</blockquote></details>

Done.

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/34)* status: all files reviewed, 3 unresolved discussions (waiting on @mkow)

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/34)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/34)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/34)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
