### PR TITLE
[LTP] Fix reporting

### PR DESCRIPTION
**Pull request by woju**
This commit adds two fixes to LTP output:

1) A summary line, indicating that LTP finished. Some developers were
confused about LTP as seen on Jenkins, because it wasn't clear that LTP
actually finished and what the result was.

2) Hide "skipped via config" messages. This is intended by the
programmer, so there is no need to remind about that.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/62)

### CODE REVIEW

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/62)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/62)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/62#-LwEfRim4r_ZDXWWcJJS:-LwEfRinEIF0iv9l4o7m:bfct6de) (no related file):*
Nice!

But I see these lines in Jenkins:
```
2019-12-16 15:13:00,117 LTP.splice02: -> SKIP (invalid shell command)
2019-12-16 15:13:08,804 LTP.clock_nanosleep02: -> SKIP (all subtests skipped (FAILED=[] NOTFOUND=[] passed=[] dontcare=[] skipped=[1, 2, 3, 4, 5, 6, 7] returncode=1))
2019-12-16 15:13:19,317 LTP: LTP finished tests=1036 failures=0 errors=0 skipped=969 returncode=0
```

Why do some tests still show `SKIP`? And I never realized this but we skip 93% of tests (969/1036), wow.

---

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/62)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/62#-LwEfRim4r_ZDXWWcJJS:-LwG0NJHAJuJdffZqnV-:buqu5ia) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Nice!

But I see these lines in Jenkins:
```
2019-12-16 15:13:00,117 LTP.splice02: -> SKIP (invalid shell command)
2019-12-16 15:13:08,804 LTP.clock_nanosleep02: -> SKIP (all subtests skipped (FAILED=[] NOTFOUND=[] passed=[] dontcare=[] skipped=[1, 2, 3, 4, 5, 6, 7] returncode=1))
2019-12-16 15:13:19,317 LTP: LTP finished tests=1036 failures=0 errors=0 skipped=969 returncode=0
```

Why do some tests still show `SKIP`? And I never realized this but we skip 93% of tests (969/1036), wow.
</blockquote></details>

Because those are not "skipped via config", but skipped for other reasons. That's intentional.

"Invalid shell command" is `seq 1 20000 | splice02` and we don't want multiple binaries per test, because that would test much more than single syscall (just from shell syntax it's fork/clone, pipe, dup2, close and exec; fork and exec are problematic). In the previous runner there was special logic that detected `|` character, which I threw out because I felt it was not robust enough and just detect shell pipes and lists.

"all subtests skipped" is a result of a binary that has nothing in must-pass and didn't pass anything (all subtests failed/broken).

Yes, we barely run anything. Most tests are unstable, but for two specific cases see oscarlab/graphene#1023 and oscarlab/graphene#1075. Especially in 1023 there are many tests that should be passing, but are failing on cleanup for some unrelated reason. 1075 is a SGX-only mmap problem.

---

**Review by dimakuv — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/62)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/62#-LwEfRim4r_ZDXWWcJJS:-LwGRPb97rIU-0rTXdiD:bvy4i8o) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Because those are not "skipped via config", but skipped for other reasons. That's intentional.

"Invalid shell command" is `seq 1 20000 | splice02` and we don't want multiple binaries per test, because that would test much more than single syscall (just from shell syntax it's fork/clone, pipe, dup2, close and exec; fork and exec are problematic). In the previous runner there was special logic that detected `|` character, which I threw out because I felt it was not robust enough and just detect shell pipes and lists.

"all subtests skipped" is a result of a binary that has nothing in must-pass and didn't pass anything (all subtests failed/broken).

Yes, we barely run anything. Most tests are unstable, but for two specific cases see oscarlab/graphene#1023 and oscarlab/graphene#1075. Especially in 1023 there are many tests that should be passing, but are failing on cleanup for some unrelated reason. 1075 is a SGX-only mmap problem.
</blockquote></details>

Thanks for explanations! True, we need to debug 1023 and make LTP great again.

---

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/62)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/62)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/62)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by yamahata — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/62)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
