### PR TITLE
[ltp] Enable more kill() regression tests; fix waitpid05 test

### PR DESCRIPTION
**Pull request by dimakuv**
This PR adds `killXX` regression tests to LTP. It also fixes `waitpid05` test.

This PR is a companion to PR on Issue https://github.com/oscarlab/graphene/issues/803. This PR must be merged into this repo first, and then the main PR must be updated to the new commit in graphene-tests submodule and merged into main Graphene repo.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/3)

### CODE REVIEW

**Review by donporter — DISMISSED** [review]
LGTM

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/3#-:-LjNP7bU47mwXy0AStMg:bb6ywmx)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by mkow — DISMISSED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/3)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by dimakuv** [comment]
Fixup to the previous commit pushed. Unfortunately, `kill06` and `kill08` leave defunct pal-Linux process behind (has to do with bugs in `shim_do_kill(process-group)`). Even though technically LTP regression tests pass, we don't want process leaks. Enabling `kill06` and `kill08` is left for future work on the IPC kill signals.

**Review by mkow — DISMISSED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/3)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Comment by dimakuv** [comment]
Fixup to the previous commit pushed. The test `vfork02` is not a sane (POSIX-complaint) program: after `vfork()`, the child process does a bunch of function calls and system calls before finally dying with `_exit()`. This is undefined behavior under POSIX and is surprising to actually work under bare Linux (e.g., the test `vfork01` doesn't work and is not added to our regression tests). So we remove `vfork02` from PASSED.

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/3)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/3)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
