### PR TITLE
[Blender] Add blender example

### PR DESCRIPTION
**Pull request by boryspoplawski**
This PR adds a new app - Blender - with a sample scene that can be rendered in CI

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/75)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/75)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[blender/blender.manifest.template, line 8 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/75#-M1aQZC2EWhFdccTmzXJ:-M1aQZC34Ei-pKwQ6Sb4:b-du4cg8) ([raw file](https://github.com/oscarlab/graphene-tests/blob/b25106470d37fdee4a5eafbfb5d87bad631bcbc7/blender/blender.manifest.template#L8)):*
> ```
> 
> loader.env.LD_LIBRARY_PATH = /graphene_lib:/blender_lib:/usr/lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu
> # graphene implicitly copies host environment variables - overwriting troublesome one
> ```

`graphene` -> `Graphene`
___
*[blender/blender.manifest.template, line 74 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/75#-M1aRlyEDloJ6lmapoez:-M1aRlyEDloJ6lmapof-:b-9o92j1) ([raw file](https://github.com/oscarlab/graphene-tests/blob/b25106470d37fdee4a5eafbfb5d87bad631bcbc7/blender/blender.manifest.template#L74)):*
> ```
> sgx.allowed_files.blender_dir = file:$(BLENDER_DIR)/$(BLENDER_VER)/
> 
> sgx.allowed_files.blender_input = file:$(DATA_DIR)/scenes/
> ```

This should be `trusted`, not `allowed`.
___
*[blender/Makefile, line 2 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/75#-M1aSLb7CwyvG8txqnVO:-M1aSLb7CwyvG8txqnVP:b658ung) ([raw file](https://github.com/oscarlab/graphene-tests/blob/b25106470d37fdee4a5eafbfb5d87bad631bcbc7/blender/Makefile#L2)):*
> ```Makefile
> # assumes this makefile lies in cwd
> PWD = $(shell pwd)
> ```

`:=` would be better here

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/75)* status: 4 of 6 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[blender/blender.manifest.template, line 8 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/75#-M1aQZC2EWhFdccTmzXJ:-M1aUCADBiF2HM9UxUsf:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/b25106470d37fdee4a5eafbfb5d87bad631bcbc7/blender/blender.manifest.template#L8)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`graphene` -> `Graphene`
</blockquote></details>

Done.
___
*[blender/blender.manifest.template, line 74 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/75#-M1aRlyEDloJ6lmapoez:-M1aUDvw7cFddDPFe-ed:b-ar8bls) ([raw file](https://github.com/oscarlab/graphene-tests/blob/b25106470d37fdee4a5eafbfb5d87bad631bcbc7/blender/blender.manifest.template#L74)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This should be `trusted`, not `allowed`.
</blockquote></details>

This is intended to allow rendering multiple scenes, even those that are not know while creating signatures.
___
*[blender/Makefile, line 2 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/75#-M1aSLb7CwyvG8txqnVO:-M1aW1Tq8KwYoGtFCVdZ:bv0jxid) ([raw file](https://github.com/oscarlab/graphene-tests/blob/b25106470d37fdee4a5eafbfb5d87bad631bcbc7/blender/Makefile#L2)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`:=` would be better here
</blockquote></details>

True, done.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/75)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[blender/blender.manifest.template, line 74 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/75#-M1aRlyEDloJ6lmapoez:-M1bw6om4uiZIXLlLaEW:b-x0ik2e) ([raw file](https://github.com/oscarlab/graphene-tests/blob/b25106470d37fdee4a5eafbfb5d87bad631bcbc7/blender/blender.manifest.template#L74)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This is intended to allow rendering multiple scenes, even those that are not know while creating signatures.
</blockquote></details>

Ok, then please put a comment here saying that this isn't secure because the enclave is running on untrusted input and in production it should be specified as `trusted_files` (most likely the scene files can easily take over the enclave execution, with some embedded python scripts or smomething).

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/75)* status: 5 of 6 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[blender/blender.manifest.template, line 74 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/75#-M1aRlyEDloJ6lmapoez:-M1epJuH0QqjnEWHbQ2F:b-f8sf1p) ([raw file](https://github.com/oscarlab/graphene-tests/blob/b25106470d37fdee4a5eafbfb5d87bad631bcbc7/blender/blender.manifest.template#L74)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ok, then please put a comment here saying that this isn't secure because the enclave is running on untrusted input and in production it should be specified as `trusted_files` (most likely the scene files can easily take over the enclave execution, with some embedded python scripts or smomething).
</blockquote></details>

Added a comment.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/75)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[blender/blender.manifest.template, line 2 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/75#-M1f-ZN_83U29QKuZqFh:-M1f-ZN_83U29QKuZqFi:b-gc8tc0) ([raw file](https://github.com/oscarlab/graphene-tests/blob/3db736d970cdbd385202405d52b385c4ef10cfa8/blender/blender.manifest.template#L2)):*
> ```
> # INSECURE!!!
> # This 3 lines are insecure by design and should never be used on production environments.
> ```

`This` -> `These`
`on production environments` -> `in production environments`
___
*[blender/blender.manifest.template, line 3 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/75#-M1f-iSP4qtl7MWP6go5:-M1f-iSP4qtl7MWP6go6:bos83me) ([raw file](https://github.com/oscarlab/graphene-tests/blob/3db736d970cdbd385202405d52b385c4ef10cfa8/blender/blender.manifest.template#L3)):*
> ```
> # INSECURE!!!
> # This 3 lines are insecure by design and should never be used on production environments.
> # There is a lot of files that blender uses (e.g. bundled python) and listing them here would
> ```

`blender` -> `Blender`
`python` -> `Python`
same below
___
*[blender/blender.manifest.template, line 6 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/75#-M1f-t9M4B1pjYko0Xm9:-M1f-t9M4B1pjYko0XmA:b-gzxgmw) ([raw file](https://github.com/oscarlab/graphene-tests/blob/3db736d970cdbd385202405d52b385c4ef10cfa8/blender/blender.manifest.template#L6)):*
> ```
> # be counter productive, as they may change between blender releases and this is just a testing
> # manifest.
> # Additionally blender scenes could allow for code execution (e.g. via bundled scripts), so running
> ```

`Additionally` -> `Additionally,`

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/75)* status: 5 of 6 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[blender/blender.manifest.template, line 2 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/75#-M1f-ZN_83U29QKuZqFh:-M1f1QSI2JEfDEtfS8ce:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/3db736d970cdbd385202405d52b385c4ef10cfa8/blender/blender.manifest.template#L2)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`This` -> `These`
`on production environments` -> `in production environments`
</blockquote></details>

Done.
___
*[blender/blender.manifest.template, line 3 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/75#-M1f-iSP4qtl7MWP6go5:-M1f1a480b5Ej1AsyLy9:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/3db736d970cdbd385202405d52b385c4ef10cfa8/blender/blender.manifest.template#L3)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`blender` -> `Blender`
`python` -> `Python`
same below
</blockquote></details>

Done.
___
*[blender/blender.manifest.template, line 6 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/75#-M1f-t9M4B1pjYko0Xm9:-M1f1ghZ23cYckDDada8:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/3db736d970cdbd385202405d52b385c4ef10cfa8/blender/blender.manifest.template#L6)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`Additionally` -> `Additionally,`
</blockquote></details>

Done.

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/75)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/75)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[blender/blender.manifest.template, line 11 at r4](https://reviewable.io/reviews/oscarlab/graphene-tests/75#-M1gwur5BIGMrU5cyoIi:-M1gwur5BIGMrU5cyoIj:b-c0qwjp) ([raw file](https://github.com/oscarlab/graphene-tests/blob/3f751c44869ae63f10797229bc190f5ace6dfdbe/blender/blender.manifest.template#L11)):*
> ```
> sgx.allowed_files.blender_dir = file:$(BLENDER_DIR)/$(BLENDER_VER)/
> sgx.allowed_files.blender_input = file:$(DATA_DIR)/scenes/
> sgx.allowed_files.blender_output = file:$(DATA_DIR)/images/
> ```

We usually have these lines in the very end of the manifest. Did you want to highlight that this is insecure by moving these lines all the way up?

Anyway, I'd prefer to have these lines in the very end.
___
*[blender/blender.manifest.template, line 49 at r4](https://reviewable.io/reviews/oscarlab/graphene-tests/75#-M1gx3JC1LQE-WXTUeOw:-M1gx3JC1LQE-WXTUeOx:bu2fg77) ([raw file](https://github.com/oscarlab/graphene-tests/blob/3f751c44869ae63f10797229bc190f5ace6dfdbe/blender/blender.manifest.template#L49)):*
> ```
> 
> 
> sys.stack.size = 8M
> ```

Is it required? The default stack (which I believe is 256KB?) is not enough for Blender?
___
*[blender/blender.manifest.template, line 52 at r4](https://reviewable.io/reviews/oscarlab/graphene-tests/75#-M1gwp7i-Uvj2BmZhsui:-M1gwp7i-Uvj2BmZhsuj:bh1lcq) ([raw file](https://github.com/oscarlab/graphene-tests/blob/3f751c44869ae63f10797229bc190f5ace6dfdbe/blender/blender.manifest.template#L52)):*
> ```
> 
> 
> sgx.enclave_size = 2048M
> ```

Does Blender really require 2GB? What does it allocate?
___
*[blender/blender.manifest.template, line 53 at r4](https://reviewable.io/reviews/oscarlab/graphene-tests/75#-M1gwd7a2KF0CUJAdmrr:-M1gwd7b9df-pyLeKwl9:bd723vz) ([raw file](https://github.com/oscarlab/graphene-tests/blob/3f751c44869ae63f10797229bc190f5ace6dfdbe/blender/blender.manifest.template#L53)):*
> ```
> 
> sgx.enclave_size = 2048M
> sgx.thread_num = 28
> ```

What is this strange number? Does it depend on the number of cores available on the host machine? What if we run this on a 48-core CPU?

Please add a comment on the logic behind this number.

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/75)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[blender/blender.manifest.template, line 11 at r4](https://reviewable.io/reviews/oscarlab/graphene-tests/75#-M1gwur5BIGMrU5cyoIi:-M1jKGWTDgJU_aTfNEdB:bfkzorn) ([raw file](https://github.com/oscarlab/graphene-tests/blob/3f751c44869ae63f10797229bc190f5ace6dfdbe/blender/blender.manifest.template#L11)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We usually have these lines in the very end of the manifest. Did you want to highlight that this is insecure by moving these lines all the way up?

Anyway, I'd prefer to have these lines in the very end.
</blockquote></details>

Yes, and we need those lines near "insecure" comment.
Summon @mkow, you insisted on it being at the top.
___
*[blender/blender.manifest.template, line 49 at r4](https://reviewable.io/reviews/oscarlab/graphene-tests/75#-M1gx3JC1LQE-WXTUeOw:-M1jLVWt0Rp309X35Pz5:bvv10bt) ([raw file](https://github.com/oscarlab/graphene-tests/blob/3f751c44869ae63f10797229bc190f5ace6dfdbe/blender/blender.manifest.template#L49)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is it required? The default stack (which I believe is 256KB?) is not enough for Blender?
</blockquote></details>

Yes, default value is not enough: we get infinite loop of full signal queue (probably all threads crashing due to lack of stack space).
I didn't dig into it, just decided that 8M isn't that much.
___
*[blender/blender.manifest.template, line 52 at r4](https://reviewable.io/reviews/oscarlab/graphene-tests/75#-M1gwp7i-Uvj2BmZhsui:-M1jN089C8qgf12L7WBJ:b-x40pl2) ([raw file](https://github.com/oscarlab/graphene-tests/blob/3f751c44869ae63f10797229bc190f5ace6dfdbe/blender/blender.manifest.template#L52)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Does Blender really require 2GB? What does it allocate?
</blockquote></details>

Yes it does (again, that might not be exact number, but 1GB was not enough). I'm not that familiar with Blender, so cannot give you detailed answer. Just rendering requires a lot of resources ;)
Also note that this is setup for the example scene we provided in this PR, rendering bigger ones probably needs some tuning (e.g. increasing memory size).
___
*[blender/blender.manifest.template, line 53 at r4](https://reviewable.io/reviews/oscarlab/graphene-tests/75#-M1gwd7a2KF0CUJAdmrr:-M1jNfl-3SVGrj4PveaI:b-9oletf) ([raw file](https://github.com/oscarlab/graphene-tests/blob/3f751c44869ae63f10797229bc190f5ace6dfdbe/blender/blender.manifest.template#L53)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is this strange number? Does it depend on the number of cores available on the host machine? What if we run this on a 48-core CPU?

Please add a comment on the logic behind this number.
</blockquote></details>

This is the number of threads that Blender (in SGX-Pal) creates in this setup. The running script specifies 4 threads to be used, so # of CPU cores should not matter.
I found it by gradually increasing `thread_num`.
Which of these information should I add as a comment (i.e. what would be useful for this manifest reader)?

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/75)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[blender/blender.manifest.template, line 53 at r4](https://reviewable.io/reviews/oscarlab/graphene-tests/75#-M1gwd7a2KF0CUJAdmrr:-M1jPnvG7NNfjvfmNrc_:b-c9zvj6) ([raw file](https://github.com/oscarlab/graphene-tests/blob/3f751c44869ae63f10797229bc190f5ace6dfdbe/blender/blender.manifest.template#L53)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This is the number of threads that Blender (in SGX-Pal) creates in this setup. The running script specifies 4 threads to be used, so # of CPU cores should not matter.
I found it by gradually increasing `thread_num`.
Which of these information should I add as a comment (i.e. what would be useful for this manifest reader)?
</blockquote></details>

Correction, the smallest number is `27`, this was rounded up

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/75)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[blender/blender.manifest.template, line 11 at r4](https://reviewable.io/reviews/oscarlab/graphene-tests/75#-M1gwur5BIGMrU5cyoIi:-M1kW-4E8qezboozwXMK:b-jif7xn) ([raw file](https://github.com/oscarlab/graphene-tests/blob/3f751c44869ae63f10797229bc190f5ace6dfdbe/blender/blender.manifest.template#L11)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yes, and we need those lines near "insecure" comment.
Summon @mkow, you insisted on it being at the top.
</blockquote></details>

I insisted on having this banner on the top, but the lines itself could IMO be moved further (and just mentioned here).

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/75)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[blender/blender.manifest.template, line 11 at r4](https://reviewable.io/reviews/oscarlab/graphene-tests/75#-M1gwur5BIGMrU5cyoIi:-M1kWkKc08wD8EIzjm-j:b-2etw9z) ([raw file](https://github.com/oscarlab/graphene-tests/blob/3f751c44869ae63f10797229bc190f5ace6dfdbe/blender/blender.manifest.template#L11)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I insisted on having this banner on the top, but the lines itself could IMO be moved further (and just mentioned here).
</blockquote></details>

IMO the lines should be right after the comment, so it's clear what it refers to.

**Review by dimakuv — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/75)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[blender/blender.manifest.template, line 11 at r4](https://reviewable.io/reviews/oscarlab/graphene-tests/75#-M1gwur5BIGMrU5cyoIi:-M1l94-K4Cwzz__naZjT:bsfwj6y) ([raw file](https://github.com/oscarlab/graphene-tests/blob/3f751c44869ae63f10797229bc190f5ace6dfdbe/blender/blender.manifest.template#L11)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

IMO the lines should be right after the comment, so it's clear what it refers to.
</blockquote></details>

No problems with that. Resolved this comment.
___
*[blender/blender.manifest.template, line 53 at r4](https://reviewable.io/reviews/oscarlab/graphene-tests/75#-M1gwd7a2KF0CUJAdmrr:-M1l9Pv30ZJejvdhbi8C:b-c79eby) ([raw file](https://github.com/oscarlab/graphene-tests/blob/3f751c44869ae63f10797229bc190f5ace6dfdbe/blender/blender.manifest.template#L53)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Correction, the smallest number is `27`, this was rounded up
</blockquote></details>

OK. Yes, then it doesn't deserve a comment. (I hoped you had a detailed explanation of what threads are added.)

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/75)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/75)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
