### PR TITLE
Remove the web-data directory

### PR DESCRIPTION
**Pull request by chiache**
The web-data directory contains tarballs of the old OSCAR websites, but they are no longer needed anymore.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/27)

### CODE REVIEW

**Review by donporter — APPROVED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/27)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/27)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/27#-LmfXkxoEsRXieHxyA-0:-LmfXkxp0ixVHJ0eGTNh:b-mrb1hx) (no related file):*
Could you please create a matching PR in the main repo, so we could test this change on Jenkins?

---

**Review by chiache — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/27)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/27#-LmfXkxoEsRXieHxyA-0:-Lmi65WS5od22hkKg94J:b6eomdr) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you please create a matching PR in the main repo, so we could test this change on Jenkins?
</blockquote></details>

https://github.com/oscarlab/graphene/pull/940.

---

**Review by donporter — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/27)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/27#-LmfXkxoEsRXieHxyA-0:-LmkHfLr3UPsZ9fYSKma:b-2izpss) (no related file):*
<details><summary><i>Previously, chiache (Chia-Che Tsai) wrote…</i></summary><blockquote>

https://github.com/oscarlab/graphene/pull/940.
</blockquote></details>

Looks like it did pass Jenkins, fwiw, so I think we could move this one forward

---

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/27)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by donporter — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/27)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
