### PR TITLE
Rewrite/Update gcc example.

### PR DESCRIPTION
**Pull request by thomasknauth**
This updates/rewrites the gcc example. It should work on Ubuntu 16.04 and 18.04 with the default gcc versions (5.5 and 7.4).

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/49)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/49)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @thomasknauth)

___
*[gcc/ld-gcc-5-trusted-files, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/49#-Lrl_r8iAQ-CtRDDoGpu:-Lrl_r8iAQ-CtRDDoGpv:bm0p1yp) ([raw file](https://github.com/oscarlab/graphene-tests/blob/1cc47dbf950b6ac7521b0f2bbe66cafd94fc3ba5/gcc/ld-gcc-5-trusted-files#L1)):*
> ```
> # Not additional gcc-5 specific trusted files required.
> ```

`No additional...` (not `not`)?
___
*[gcc/ld-gcc-7-trusted-files, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/49#-Lrla-sP6J8jzwyBmdSH:-Lrla-sP6J8jzwyBmdSI:bughblc) ([raw file](https://github.com/oscarlab/graphene-tests/blob/1cc47dbf950b6ac7521b0f2bbe66cafd94fc3ba5/gcc/ld-gcc-7-trusted-files#L1)):*
> ```
> sgx.trusted_files.crtbeginSo = file:/usr/lib/gcc/x86_64-linux-gnu/7/crtbeginS.o\nsgx.trusted_files.libgccsso = file:/usr/lib/gcc/x86_64-linux-gnu/7/libgcc_s.so.1\nsgx.trusted_files.crtendSo = file:/usr/lib/gcc/x86_64-linux-gnu/7/crtendS.o
> ```

I'm not sure why this file contains `\n`. Wouldn't normal line breaks work?
___
*[gcc/Makefile, line 33 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/49#-LrlaWlvChKJuT0tscLq:-LrlaWlvChKJuT0tscLr:b-ossslo) ([raw file](https://github.com/oscarlab/graphene-tests/blob/1cc47dbf950b6ac7521b0f2bbe66cafd94fc3ba5/gcc/Makefile#L33)):*
> ```Makefile
> 		-e 's|$$(GRAPHENEDEBUG)|'"$(GRAPHENEDEBUG)"'|g' \
> 		-e 's|$$(INSTALL_DIR)|'"$(INSTALL_DIR)"'|g' \
> 		-e 's|$$(INSTALL_DIR_ABSPATH)|'"$(abspath $(INSTALL_DIR))"'|g' \
> ```

`INSTALL_DIR` and `INSTALL_DIR_ABSPATH` are not used, can be deleted from here
___
*[gcc/Makefile, line 43 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/49#-LrlaiCD-iU1mtpgrDQ1:-LrlaiCD-iU1mtpgrDQ2:bs839xf) ([raw file](https://github.com/oscarlab/graphene-tests/blob/1cc47dbf950b6ac7521b0f2bbe66cafd94fc3ba5/gcc/Makefile#L43)):*
> ```Makefile
> .SECONDARY: $(addsuffix .manifest.sgx, $(TOOLS))
> 
> # Rules to generate the SGX-specific manifest (.manifesg.sgx), the enclave signature (.sig), and the
> ```

`manifesg` -> `manifest`

**Review by thomasknauth — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/49)* status: 13 of 15 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[gcc/ld-gcc-5-trusted-files, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/49#-Lrl_r8iAQ-CtRDDoGpu:-LroTRcw2Q91vpMK7BKI:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/1cc47dbf950b6ac7521b0f2bbe66cafd94fc3ba5/gcc/ld-gcc-5-trusted-files#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`No additional...` (not `not`)?
</blockquote></details>

Done.
___
*[gcc/ld-gcc-7-trusted-files, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/49#-Lrla-sP6J8jzwyBmdSH:-LroTUtW5kho6ErXAswD:bm3um4b) ([raw file](https://github.com/oscarlab/graphene-tests/blob/1cc47dbf950b6ac7521b0f2bbe66cafd94fc3ba5/gcc/ld-gcc-7-trusted-files#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm not sure why this file contains `\n`. Wouldn't normal line breaks work?
</blockquote></details>

If you have actual newlines, it breaks the sed command. Its the same format as produced by the %-trusted-libs target, e.g., make cc1-trusted-libs for this example.
___
*[gcc/Makefile, line 33 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/49#-LrlaWlvChKJuT0tscLq:-LroU3gU6_8Dq4AYDy5o:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/1cc47dbf950b6ac7521b0f2bbe66cafd94fc3ba5/gcc/Makefile#L33)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`INSTALL_DIR` and `INSTALL_DIR_ABSPATH` are not used, can be deleted from here
</blockquote></details>

Done.
___
*[gcc/Makefile, line 43 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/49#-LrlaiCD-iU1mtpgrDQ1:-LroU9DfDO31w8vGtZ2Y:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/1cc47dbf950b6ac7521b0f2bbe66cafd94fc3ba5/gcc/Makefile#L43)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`manifesg` -> `manifest`
</blockquote></details>

Done.

**Review by dimakuv — DISMISSED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/49)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by dimakuv — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/49)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Comment by dimakuv** [comment]
I had to rebase this PR to current master because it got de-synchronized with the main Graphene repo. The root cause was that this PR didn't contain the updated LTP dir, whereas the main Graphene repo had Jenkinsfiles expecting the updated LTP. So all Jenkins pipelines failed.

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/49)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/49)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 13 of 15 files at r1, 1 of 2 files at r2, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/49)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @thomasknauth)

___
*[gcc/ld.manifest.template, line 39 at r4](https://reviewable.io/reviews/oscarlab/graphene-tests/49#-LrptYpI0YUv1_sYAPMM:-LrptYpI0YUv1_sYAPMN:b7rtz1w) ([raw file](https://github.com/oscarlab/graphene-tests/blob/6e43225f7130bbf9fe45f0ad6e70f87a63c6a02a/gcc/ld.manifest.template#L39)):*
> ```
> sgx.trusted_files.libgcca = file:/usr/lib/gcc/x86_64-linux-gnu/$(GCC_MAJOR_VERSION)/libgcc.a
> sgx.trusted_files.crtend = file:/usr/lib/gcc/x86_64-linux-gnu/$(GCC_MAJOR_VERSION)/crtend.o
> sgx.trusted_files.crtbegin = file:/usr/lib/gcc/x86_64-linux-gnu/$(GCC_MAJOR_VERSION)/crtbegin.o
> ```

Please make this path configurable through Make flags, this location is distro-specific. E.g. on one of my machines I have those files under `/usr/lib/gcc/x86_64-redhat-linux/`.
Same for other manifest templates.
___
*[gcc/Makefile, line 2 at r4](https://reviewable.io/reviews/oscarlab/graphene-tests/49#-Lrpv2tW2MsjypGFeXtb:-Lrpv2tW2MsjypGFeXtc:b-rankln) ([raw file](https://github.com/oscarlab/graphene-tests/blob/6e43225f7130bbf9fe45f0ad6e70f87a63c6a02a/gcc/Makefile#L2)):*
> ```Makefile
> THIS_DIR := $(dir $(lastword $(MAKEFILE_LIST)))
> ifeq ($(THIS_DIR), ./)  # workaround Graphene issue #1044 with allowed_files
> ```

#1044 is already fixed.
___
*[gcc/Makefile, line 34 at r4](https://reviewable.io/reviews/oscarlab/graphene-tests/49#-LrpwXaCDMv5YUZBxMGh:-LrpwXaCDMv5YUZBxMGi:b9wu4vi) ([raw file](https://github.com/oscarlab/graphene-tests/blob/6e43225f7130bbf9fe45f0ad6e70f87a63c6a02a/gcc/Makefile#L34)):*
> ```
> cat cc1-trusted-libs
> ```

Does this file exists? I don't see it in the PR.
___
*[gcc/Makefile, line 50 at r4](https://reviewable.io/reviews/oscarlab/graphene-tests/49#-LrpvZii5ScYxl7KMYlt:-LrpvZii5ScYxl7KMYlu:b-9mey3g) ([raw file](https://github.com/oscarlab/graphene-tests/blob/6e43225f7130bbf9fe45f0ad6e70f87a63c6a02a/gcc/Makefile#L50)):*
> ```Makefile
> 
> # .sig file is actually generated by the above target %.manifest.sgx. The %.sig target is required
> # to tell make this. Also, the rule must actually have at least one command, otherwise it does not
> ```

Please wrap `make` in backticks in this sentence. I had to read it twice to notice that it's not used as a verb here ;)
___
*[gcc/Makefile, line 91 at r4](https://reviewable.io/reviews/oscarlab/graphene-tests/49#-LrpxAzN75S8TU0KofRz:-LrpxAzN75S8TU0KofS-:b-1g20hh) ([raw file](https://github.com/oscarlab/graphene-tests/blob/6e43225f7130bbf9fe45f0ad6e70f87a63c6a02a/gcc/Makefile#L91)):*
> ```Makefile
> 	done > $@
> 
> regression: all
> ```

missing `.PHONY`
___
*[gcc/README.md, line 13 at r4](https://reviewable.io/reviews/oscarlab/graphene-tests/49#-Lrps3j2EzuHi40uOD5l:-Lrps3j2EzuHi40uOD5m:b391sxx) ([raw file](https://github.com/oscarlab/graphene-tests/blob/6e43225f7130bbf9fe45f0ad6e70f87a63c6a02a/gcc/README.md#L13)):*
> ```Markdown
> # Quick Start
> 
> To run the regression tests execute ```make regression```. To do the same for SGX, execute ```SGX=1
> ```

We use `test` or `check` in new directories, this `regression` target in the main repo will also be renamed soon.

**Review by thomasknauth — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/49)* status: 9 of 15 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @mkow)

___
*[gcc/ld.manifest.template, line 39 at r4](https://reviewable.io/reviews/oscarlab/graphene-tests/49#-LrptYpI0YUv1_sYAPMM:-Ls3W0byE5acxqPc-bPm:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/6e43225f7130bbf9fe45f0ad6e70f87a63c6a02a/gcc/ld.manifest.template#L39)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please make this path configurable through Make flags, this location is distro-specific. E.g. on one of my machines I have those files under `/usr/lib/gcc/x86_64-redhat-linux/`.
Same for other manifest templates.
</blockquote></details>

Done.
___
*[gcc/Makefile, line 2 at r4](https://reviewable.io/reviews/oscarlab/graphene-tests/49#-Lrpv2tW2MsjypGFeXtb:-Ls3TqZd3zGCoIxxocPf:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/6e43225f7130bbf9fe45f0ad6e70f87a63c6a02a/gcc/Makefile#L2)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

#1044 is already fixed.
</blockquote></details>

Done.
___
*[gcc/Makefile, line 34 at r4](https://reviewable.io/reviews/oscarlab/graphene-tests/49#-LrpwXaCDMv5YUZBxMGh:-Ls3W2HaEzKYVn9yGDhq:bqcx4ck) ([raw file](https://github.com/oscarlab/graphene-tests/blob/6e43225f7130bbf9fe45f0ad6e70f87a63c6a02a/gcc/Makefile#L34)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> cat cc1-trusted-libs
> ```

Does this file exists? I don't see it in the PR.
</blockquote></details>

There is a target %-trusted-libs to generate it.
___
*[gcc/Makefile, line 50 at r4](https://reviewable.io/reviews/oscarlab/graphene-tests/49#-LrpvZii5ScYxl7KMYlt:-Ls3WTbW0qBvWPJycgqP:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/6e43225f7130bbf9fe45f0ad6e70f87a63c6a02a/gcc/Makefile#L50)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please wrap `make` in backticks in this sentence. I had to read it twice to notice that it's not used as a verb here ;)
</blockquote></details>

Done.
___
*[gcc/Makefile, line 91 at r4](https://reviewable.io/reviews/oscarlab/graphene-tests/49#-LrpxAzN75S8TU0KofRz:-Ls3W_ZpDwZWTH5MAyiT:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/6e43225f7130bbf9fe45f0ad6e70f87a63c6a02a/gcc/Makefile#L91)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

missing `.PHONY`
</blockquote></details>

Done.
___
*[gcc/README.md, line 13 at r4](https://reviewable.io/reviews/oscarlab/graphene-tests/49#-Lrps3j2EzuHi40uOD5l:-Ls3ZWnk0bDUpDBXt-UT:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/6e43225f7130bbf9fe45f0ad6e70f87a63c6a02a/gcc/README.md#L13)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

We use `test` or `check` in new directories, this `regression` target in the main repo will also be renamed soon.
</blockquote></details>

Done.

**Review by dimakuv — DISMISSED** [review]
> Reviewed 6 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/49)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

**Review by mkow — DISMISSED** [review]
> Reviewed 6 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/49)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/49)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/49)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
