### PR TITLE
Remove make and openjdk from the apps directory

### PR DESCRIPTION
**Pull request by chiache**
These two applications are currently not fully working. Removed from the main repository.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/26)

### CODE REVIEW

**Review by donporter — CHANGES_REQUESTED** [review]
> Reviewed 29 of 29 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/26)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/26#-Lme9fnhE5l6fbFDHEak:-Lme9fni2xsoM5ZNxvaz:bgurg3t) (no related file):*
I assume you will put them in a branch?  I feel like Java and Make are both worth resurrecting at some point.

---

**Review by donporter — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/26)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache)

**Review by mkow — APPROVED** [review]
> Reviewed 29 of 29 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/26)* status: all files reviewed, 1 unresolved discussion (waiting on @chiache)

**Review by mkow — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/26)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/26#-LmfYnTHBmN1ur0wpjhh:-LmfYnTHBmN1ur0wpjhi:b-oind8z) (no related file):*
 Could you please create a matching PR in the main repo?

---

**Review by chiache — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/26)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/26#-Lme9fnhE5l6fbFDHEak:-Lmi5xDpAngE38LOzHHu:bhy9ot6) (no related file):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

I assume you will put them in a branch?  I feel like Java and Make are both worth resurrecting at some point.
</blockquote></details>

Will do.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/26#-LmfYnTHBmN1ur0wpjhh:-Lmi5vz57rlJxPFojZhK:bg8uqp5) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

 Could you please create a matching PR in the main repo?
</blockquote></details>

https://github.com/oscarlab/graphene/pull/939

---

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/26)* status: all files reviewed, 1 unresolved discussion (waiting on @chiache)

**Review by donporter — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/26)* status: all files reviewed, 1 unresolved discussion (waiting on @chiache)

**Review by donporter — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/26)* status: all files reviewed, 1 unresolved discussion (waiting on @chiache)

**Pull request merged**
