### PR TITLE
Decouple TF build from Graphene's build system

### PR DESCRIPTION
**Pull request by thomasknauth**
This PR consolidates two Makefiles into one and removes dependencies on Graphene's build system.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/48)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
@yamahata @hw42 Could one of you take a quick look at this?

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/48#-:-Lqhs1dk6n3NXp00-bMh:b-vkcth7)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @thomasknauth)

___
*[tensorflow/Makefile, line 7 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/48#-LqhsZSj5nRnviSSGfUO:-LqhsZSk6bG7AbXCaTOB:b-4d51gd) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a31d31021291972d2e77dc5136a88179185038d/tensorflow/Makefile#L7)):*
> ```Makefile
> GRAPHENEDIR=../../../../..
> TF_DIR ?= tensorflow
> BAZEL_BIN ?= $(HOME)/bin/bazel
> ```

home? sounds like a weird default, I think people/distros install it somewhere else usually.
___
*[tensorflow/Makefile, line 11 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/48#-LqhstBV15kyt1bRczvV:-LqhstBV15kyt1bRczvW:b8qpg50) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a31d31021291972d2e77dc5136a88179185038d/tensorflow/Makefile#L11)):*
> ```Makefile
> tensorflow/configure:
> 	git clone https://github.com/tensorflow/tensorflow
> 	cd tensorflow && git checkout tags/v1.9.0
> ```

Please do the checkout by a hardcoded hash (and place the tag in the comment) + move this to a configuration variable
___
*[tensorflow/Makefile, line 24 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/48#-Lqhtzhf9jdE0HTMrKr3:-Lqhtzhf9jdE0HTMrKr4:b-6jp2xw) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a31d31021291972d2e77dc5136a88179185038d/tensorflow/Makefile#L24)):*
> ```Makefile
> 
> inception_v3.tflite:
> 	wget https://storage.googleapis.com/download.tensorflow.org/models/tflite/model_zoo/upload_20180427/inception_v3_2018_04_27.tgz
> ```

Please verify all downloads by hashes (see some other samples, I think we do it this way there)
___
*[tensorflow/Makefile, line 69 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/48#-Lqhu_VE3pdYMRReCC3h:-Lqhu_VE3pdYMRReCC3i:bt32xt5) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a31d31021291972d2e77dc5136a88179185038d/tensorflow/Makefile#L69)):*
> ```Makefile
> .PHONY: clean
> clean:
> 	$(RM) -f label_image.manifest label_image.manifest.sgx label_image.sig label_image.token
> ```

`$(RM)` already includes `-f` by default (same for the 2 occurrences below)
___
*[tensorflow/Makefile, line 81 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/48#-Lqhuv4a5kc_7oveEbtw:-Lqhuv4b20KWnHwfZC4s:b1wi77x) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a31d31021291972d2e77dc5136a88179185038d/tensorflow/Makefile#L81)):*
> ```Makefile
> 	apt-get update
> 	apt-get install -y python-dev python-pip wget git
> # https://docs.bazel.build/versions/master/install-ubuntu.html
> ```

Please indent it on the same level as the commands
___
*[tensorflow/Makefile, line 83 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/48#-LqhvBlf0vZlPq8Rm0aN:-LqhvBlgDX5YrRLAQOlh:bsgwb43) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a31d31021291972d2e77dc5136a88179185038d/tensorflow/Makefile#L83)):*
> ```Makefile
> # https://docs.bazel.build/versions/master/install-ubuntu.html
> 	apt-get install -y pkg-config zip g++ zlib1g-dev unzip python
> 	wget https://github.com/bazelbuild/bazel/releases/download/0.16.1/bazel-0.16.1-installer-linux-x86_64.sh
> ```

Please verify the download by a hash

**Review by thomasknauth — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/48)* status: 2 of 3 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

___
*[tensorflow/Makefile, line 7 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/48#-LqhsZSj5nRnviSSGfUO:-LqlQvt39dAV_lQyk4nX:b-lyq73k) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a31d31021291972d2e77dc5136a88179185038d/tensorflow/Makefile#L7)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

home? sounds like a weird default, I think people/distros install it somewhere else usually.
</blockquote></details>

This is where Bazel will install itself by default.
___
*[tensorflow/Makefile, line 11 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/48#-LqhstBV15kyt1bRczvV:-LqlWsqB0mbtZ_sKnEVS:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a31d31021291972d2e77dc5136a88179185038d/tensorflow/Makefile#L11)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please do the checkout by a hardcoded hash (and place the tag in the comment) + move this to a configuration variable
</blockquote></details>

Done.
___
*[tensorflow/Makefile, line 24 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/48#-Lqhtzhf9jdE0HTMrKr3:-LqlXcKG4Yc7FLQLuwi0:b-dunp7z) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a31d31021291972d2e77dc5136a88179185038d/tensorflow/Makefile#L24)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please verify all downloads by hashes (see some other samples, I think we do it this way there)
</blockquote></details>

Seriously? It uses HTTPS. Do we trust the user's compiler no to sneak a backdoor in there somewhere? This is just an example.
___
*[tensorflow/Makefile, line 69 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/48#-Lqhu_VE3pdYMRReCC3h:-LqlYCmEA41yPdx3CaB1:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a31d31021291972d2e77dc5136a88179185038d/tensorflow/Makefile#L69)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`$(RM)` already includes `-f` by default (same for the 2 occurrences below)
</blockquote></details>

Done.
___
*[tensorflow/Makefile, line 81 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/48#-Lqhuv4a5kc_7oveEbtw:-LqlYI0s3yVBYdRABsGf:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a31d31021291972d2e77dc5136a88179185038d/tensorflow/Makefile#L81)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please indent it on the same level as the commands
</blockquote></details>

Done.
___
*[tensorflow/Makefile, line 83 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/48#-LqhvBlf0vZlPq8Rm0aN:-LqlZjBwEm4vsUXiCqXL:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a31d31021291972d2e77dc5136a88179185038d/tensorflow/Makefile#L83)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please verify the download by a hash
</blockquote></details>

Done.

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/48)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/48)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[tensorflow/Makefile, line 24 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/48#-Lqhtzhf9jdE0HTMrKr3:-LrpjKpR4cVzeyXRAXi8:brgrhmh) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a31d31021291972d2e77dc5136a88179185038d/tensorflow/Makefile#L24)):*
I prefer to always fetch all external resources by hash, just as a good practice. This way we'll also detect some accidental / unexpected changes to those files (e.g. if for some reason the owners decide to patch something in there) and incomplete downloads.
Also, this is such a complicated task only in Make, CMake has builtin commands for fetching with hash checking.

> Do we trust the user's compiler no to sneak a backdoor in there somewhere? This is just an example.

If the compiler was being downloaded before building from some third-party server then I'd also verify its hash ;)

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/48)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/48)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by yamahata — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/48)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
