### PR TITLE
Add OpenVINO example

### PR DESCRIPTION
**Pull request by dimakuv**
Adds OpenVINO example.

OpenVINO uncovered some bugs in Graphene/Graphene-SGX:
* https://github.com/oscarlab/graphene/pull/1064
* https://github.com/oscarlab/graphene/pull/1065
* https://github.com/oscarlab/graphene/pull/1066

They all should be merged into Graphene to be able to run OpenVINO correctly to completion.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/47)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/47)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[openvino/.gitignore, line 3 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/47#-LqYdmAz7nW1sEcsvy-a:-LqYdmAz7nW1sEcsvy-b:b-vqr1ul) ([raw file](https://github.com/oscarlab/graphene-tests/blob/783b7b7e8f890ce8b638a52378aea3f6a4555e0f/openvino/.gitignore#L3)):*
> ```ignore
> *.bmp
> /openvino
> /model
> ```

those two are directories? if so, please add trailing `/`
___
*[openvino/Makefile, line 6 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/47#-LqYeUwo42FPf7mWUwx5:-LqYeUwo42FPf7mWUwx6:bkdjd3g) ([raw file](https://github.com/oscarlab/graphene-tests/blob/783b7b7e8f890ce8b638a52378aea3f6a4555e0f/openvino/Makefile#L6)):*
> ```Makefile
> # - make DEBUG=1          Building for Linux, with Graphene debug output
> # - make SGX=1            Building for SGX
> # - make SGX=1 DEBUG=1    Building for SGX, with Graphene debug output
> ```

This DEBUG switch seems to also influence OpenVINO according to this Makefile, not only Graphene.
___
*[openvino/Makefile, line 6 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/47#-LqYency54w1efhahc8W:-LqYency54w1efhahc8X:b-da1d7v) ([raw file](https://github.com/oscarlab/graphene-tests/blob/783b7b7e8f890ce8b638a52378aea3f6a4555e0f/openvino/Makefile#L6)):*
> ```Makefile
> # - make DEBUG=1          Building for Linux, with Graphene debug output
> # - make SGX=1            Building for SGX
> # - make SGX=1 DEBUG=1    Building for SGX, with Graphene debug output
> ```

I think it should be "builds" or "build" for the command annotation, "-ing" seems a bit weird to me here.
___
*[openvino/Makefile, line 46 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/47#-LqYf_TuAeyfh8IUjJ6A:-LqYf_TvEVEhSNxBw_n8:b-kodscb) ([raw file](https://github.com/oscarlab/graphene-tests/blob/783b7b7e8f890ce8b638a52378aea3f6a4555e0f/openvino/Makefile#L46)):*
> ```Makefile
> $(MODEL_DIR)/README.md:
> 	git clone https://github.com/opencv/open_model_zoo.git $(MODEL_DIR)
> 	cd $(MODEL_DIR) && git checkout $(MODEL_VERSION)
> ```

Could you do the checkout by hash? (and comment to which version it corresponds to).
This way we can be 100% sure that we get exactly the same version as checked by you when preparing the integration.
___
*[openvino/Makefile, line 58 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/47#-LqYg7jp-cqhrjEje-Hx:-LqYg7jp-cqhrjEje-Hy:b-927xgh) ([raw file](https://github.com/oscarlab/graphene-tests/blob/783b7b7e8f890ce8b638a52378aea3f6a4555e0f/openvino/Makefile#L58)):*
> ```Makefile
> $(OPENVINO_DIR)/README.md:
> 	git clone https://github.com/opencv/dldt.git $(OPENVINO_DIR)
> 	cd $(OPENVINO_DIR) && git checkout $(OPENVINO_VERSION)
> ```

ditto (checkout by hash)
___
*[openvino/Makefile, line 65 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/47#-LqYga2D8NfrRNPGmqEZ:-LqYga2D8NfrRNPGmqE_:b-f8da6z) ([raw file](https://github.com/oscarlab/graphene-tests/blob/783b7b7e8f890ce8b638a52378aea3f6a4555e0f/openvino/Makefile#L65)):*
> ```Makefile
> 	cd $(OPENVINO_DIR)/inference-engine && mkdir -p build
> 	cd $(OPENVINO_DIR)/inference-engine/build && cmake -DCMAKE_BUILD_TYPE=$(OPENVINO_BUILD) ..
> 	$(MAKE) -j4 -C $(OPENVINO_DIR)/inference-engine/build
> ```

no need to hardcode `-j4` here, I think it will be inherited from the main `make` invocation
___
*[openvino/README.md, line 3 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/47#-LqYiSaB-fikh51yMEQs:-LqYiSaB-fikh51yMEQt:b-ctfl75) ([raw file](https://github.com/oscarlab/graphene-tests/blob/783b7b7e8f890ce8b638a52378aea3f6a4555e0f/openvino/README.md#L3)):*
> ```Markdown
> # OpenVINO
> 
> This directory contains the Makefile and the template manifest for the most
> ```

`the Makefile and the template`
I think it should be "a" x2
___
*[openvino/images/horse.jpg, line 0 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/47#-LqYhQuLEAqUJxl1NROH:-LqYhQuLEAqUJxl1NROI:b-2m1ar5) ([raw file](https://github.com/oscarlab/graphene-tests/blob/783b7b7e8f890ce8b638a52378aea3f6a4555e0f/openvino/images/horse.jpg#L0)):*
Those are actually hors*es*, not a horse! ;)

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/47)* status: 1 of 5 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[openvino/.gitignore, line 3 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/47#-LqYdmAz7nW1sEcsvy-a:-LqbVs2_9fzPvpZYs0JA:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/783b7b7e8f890ce8b638a52378aea3f6a4555e0f/openvino/.gitignore#L3)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

those two are directories? if so, please add trailing `/`
</blockquote></details>

Done.
___
*[openvino/Makefile, line 6 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/47#-LqYeUwo42FPf7mWUwx5:-LqbWiW56lPdsWmUyfDZ:b-376vyb) ([raw file](https://github.com/oscarlab/graphene-tests/blob/783b7b7e8f890ce8b638a52378aea3f6a4555e0f/openvino/Makefile#L6)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This DEBUG switch seems to also influence OpenVINO according to this Makefile, not only Graphene.
</blockquote></details>

Done. Good catch.
___
*[openvino/Makefile, line 6 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/47#-LqYency54w1efhahc8W:-LqbWqkT8T5GHDEDzygQ:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/783b7b7e8f890ce8b638a52378aea3f6a4555e0f/openvino/Makefile#L6)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think it should be "builds" or "build" for the command annotation, "-ing" seems a bit weird to me here.
</blockquote></details>

Done.
___
*[openvino/Makefile, line 46 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/47#-LqYf_TuAeyfh8IUjJ6A:-LqbZ8plEeQDr9CWw7Uj:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/783b7b7e8f890ce8b638a52378aea3f6a4555e0f/openvino/Makefile#L46)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you do the checkout by hash? (and comment to which version it corresponds to).
This way we can be 100% sure that we get exactly the same version as checked by you when preparing the integration.
</blockquote></details>

Done.
___
*[openvino/Makefile, line 58 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/47#-LqYg7jp-cqhrjEje-Hx:-LqbZB3w87X5ayuA4_HC:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/783b7b7e8f890ce8b638a52378aea3f6a4555e0f/openvino/Makefile#L58)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto (checkout by hash)
</blockquote></details>

Done.
___
*[openvino/Makefile, line 65 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/47#-LqYga2D8NfrRNPGmqEZ:-LqbZH0X7qSoqL2pA8Ov:bdq7tqn) ([raw file](https://github.com/oscarlab/graphene-tests/blob/783b7b7e8f890ce8b638a52378aea3f6a4555e0f/openvino/Makefile#L65)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

no need to hardcode `-j4` here, I think it will be inherited from the main `make` invocation
</blockquote></details>

Done. True, that was a historic artifact.
___
*[openvino/README.md, line 3 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/47#-LqYiSaB-fikh51yMEQs:-LqbZYIy2aB6TqqCjR7U:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/783b7b7e8f890ce8b638a52378aea3f6a4555e0f/openvino/README.md#L3)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`the Makefile and the template`
I think it should be "a" x2
</blockquote></details>

Done.
___
*[openvino/images/horse.jpg, line  at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/47#-LqYhQuLEAqUJxl1NROH:-LqbZm9j2p2vc2EF13E-:b-xwdujg) ([raw file](https://github.com/oscarlab/graphene-tests/blob/783b7b7e8f890ce8b638a52378aea3f6a4555e0f/openvino/images/horse.jpg#L)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Those are actually hors*es*, not a horse! ;)
</blockquote></details>

Done. This is a new level of reviewing from Michal :)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/47)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[openvino/Makefile, line 6 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/47#-LqYency54w1efhahc8W:-LqfE94VDedJxFW-WpAO:bysppcp) ([raw file](https://github.com/oscarlab/graphene-tests/blob/783b7b7e8f890ce8b638a52378aea3f6a4555e0f/openvino/Makefile#L6)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I meant only command annotations, as a paragraph title it should be with -ing.
___
*[openvino/images/horse.jpg, line  at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/47#-LqYhQuLEAqUJxl1NROH:-LqfFA4PEB907bnrsQSz:b9v5a3j) ([raw file](https://github.com/oscarlab/graphene-tests/blob/783b7b7e8f890ce8b638a52378aea3f6a4555e0f/openvino/images/horse.jpg#L)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. This is a new level of reviewing from Michal :)
</blockquote></details>

:D
I guess this should be now called "image review", not only 'code review" :)

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/47)* status: 4 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[openvino/Makefile, line 6 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/47#-LqYency54w1efhahc8W:-LqhJ-raESeOAzBFwveE:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/783b7b7e8f890ce8b638a52378aea3f6a4555e0f/openvino/Makefile#L6)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I meant only command annotations, as a paragraph title it should be with -ing.
</blockquote></details>

Done.

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/47)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by thomasknauth — COMMENTED** [review]
Found a few minor issues. Had to stop in the middle of reviewing though. Sorry.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/47#-:-LqvKWBiBk4lktZ-d5o1:bntsngt)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[openvino/README.md, line 24 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/47#-LqsKFThDeOzRNuZS5DK:-LqsKFTi8Tlm3ueOPa1D:bp0evtz) ([raw file](https://github.com/oscarlab/graphene-tests/blob/682a72c01c97d5c193a134069521f6b936b86712/openvino/README.md#L24)):*
> ```Markdown
> For Ubuntu 16.04, install the following prerequisite packages:
> 
> * Install the newest CMake (on Ubuntu 16.04, this may require installing Cmake
> ```

Can you specify a specific version, i.e.,  >= 3.7.2? Maybe I already have a sufficiently recent version installed. Hard to tell currently.
___
*[openvino/README.md, line 36 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/47#-LqsMSXW6tZGzHjD65I8:-LqsMSXX4jfb5DuGF0ca:b-j90fwb) ([raw file](https://github.com/oscarlab/graphene-tests/blob/682a72c01c97d5c193a134069521f6b936b86712/openvino/README.md#L36)):*
> ```Markdown
> # note that it also downloads the SSD300 model and transforms it from the Caffe
> # format to an optimized Intermediate Representation (IR)
> make SGX=1
> ```

I had to install the package libusb-1.0.0.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/47)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @thomasknauth)

___
*[openvino/README.md, line 36 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/47#-LqsMSXW6tZGzHjD65I8:-LrC4zz-8nhXhuwRVQBK:b-4oaoh7) ([raw file](https://github.com/oscarlab/graphene-tests/blob/682a72c01c97d5c193a134069521f6b936b86712/openvino/README.md#L36)):*
<details><summary><i>Previously, thomasknauth (Thomas Knauth) wrote…</i></summary><blockquote>

I had to install the package libusb-1.0.0.
</blockquote></details>

True. Note for myself: also need to install `pip3 install --upgrade protobuf==3.6.1`

**Review by thomasknauth — COMMENTED** [review]
Was able to execute the code.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/47#-:-LrLkP14CRPVLwM_pKgP:bjlh030)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[openvino/README.md, line 49 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/47#-LrLkTkCDxYQ9-EmfzPl:-LrLkTkCDxYQ9-EmfzPm:b-oihmy6) ([raw file](https://github.com/oscarlab/graphene-tests/blob/682a72c01c97d5c193a134069521f6b936b86712/openvino/README.md#L49)):*
> ```Markdown
> 
> # Each of these commands produces an image out_0.bmp with detected objects
> xxd out_0.bmp   # or open in any image editor
> ```

Like your humor here. One day you have to teach me how to mentally turn the columns of hexadecimals characters coming out of xxd back into a picture before my "internal eye". :)

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/47)* status: 4 of 5 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @thomasknauth)

___
*[openvino/README.md, line 24 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/47#-LqsKFThDeOzRNuZS5DK:-LrLtZaNDnHceBT6Q0nA:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/682a72c01c97d5c193a134069521f6b936b86712/openvino/README.md#L24)):*
<details><summary><i>Previously, thomasknauth (Thomas Knauth) wrote…</i></summary><blockquote>

Can you specify a specific version, i.e.,  >= 3.7.2? Maybe I already have a sufficiently recent version installed. Hard to tell currently.
</blockquote></details>

Done.
___
*[openvino/README.md, line 49 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/47#-LrLkTkCDxYQ9-EmfzPl:-LrLtbVs5ZM9hzm30cMw:b-schc6r) ([raw file](https://github.com/oscarlab/graphene-tests/blob/682a72c01c97d5c193a134069521f6b936b86712/openvino/README.md#L49)):*
<details><summary><i>Previously, thomasknauth (Thomas Knauth) wrote…</i></summary><blockquote>

Like your humor here. One day you have to teach me how to mentally turn the columns of hexadecimals characters coming out of xxd back into a picture before my "internal eye". :)
</blockquote></details>

This is just so a person sees that there is indeed some content dumped in the file. Also, a trained programmer may recognize the BMP header in the first bytes. (Please mark as Satisfied if you're happy with this answer).

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/47)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/47)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
