### PR TITLE
Image classification with PyTorch

### PR DESCRIPTION
**Pull request by thomasknauth**
This PR includes an example of running PyTorch on Graphene. A pre-trained machine learning model is used for image classification.

Tested on 3 different systems. Tested with Ubuntu 16 and 18.

Corresponding PR is https://github.com/oscarlab/graphene/pull/1356.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/66)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/66)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @thomasknauth)

___
*[pytorch/Makefile, line 10 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/66#-LzIo2nICGN9llXYyI00:-LzIo2nICGN9llXYyI01:b-cbpuwt) ([raw file](https://github.com/oscarlab/graphene-tests/blob/e2562c76d3135a4ea4e0165987cee7320a482b0a/pytorch/Makefile#L10)):*
> ```Makefile
> 
> DISTRIB_ID ?= $(shell grep _ID /etc/lsb-release | cut -d= -f2)
> DISTRIB_RLEASE_MAJOR ?= $(shell grep _RELEASE /etc/lsb-release | cut -d= -f 2 | cut -d. -f 1)
> ```

`RLEASE` -> `RELEASE`. Not blocking on this, maybe that's what you wanted.
___
*[pytorch/Makefile, line 19 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/66#-LzIoDn45Q5DNAdOHzuU:-LzIoDn45Q5DNAdOHzuV:bvh6xie) ([raw file](https://github.com/oscarlab/graphene-tests/blob/e2562c76d3135a4ea4e0165987cee7320a482b0a/pytorch/Makefile#L19)):*
> ```Makefile
> 
> .PHONY: default
> default: pytorch.token python3.token
> ```

What if the user wants to build non-SGX version? Please make it similar to other cases where we have `if (SGX) ...`.
___
*[pytorch/Makefile, line 29 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/66#-LzIoZA3DyOxBXfQ6ByG:-LzIoZA3DyOxBXfQ6ByH:b1eqjz) ([raw file](https://github.com/oscarlab/graphene-tests/blob/e2562c76d3135a4ea4e0165987cee7320a482b0a/pytorch/Makefile#L29)):*
> ```Makefile
> 		-e 's|$$(GRAPHENEDEBUG)|'"$(GRAPHENEDEBUG)"'|g' \
> 		-e 's|$$(HOME)|'"$(HOME)"'|g' \
> 		-e 's|# '"$(UBUNTU_VERSION)"' ||g' \
> ```

Oh, that is pretty smart! We should use this trick in the future.
___
*[pytorch/Makefile, line 33 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/66#-LzIpCb34VIRmB5K1TO1:-LzIpCb34VIRmB5K1TO2:bvutbzy) ([raw file](https://github.com/oscarlab/graphene-tests/blob/e2562c76d3135a4ea4e0165987cee7320a482b0a/pytorch/Makefile#L33)):*
> ```Makefile
> 
> pytorch.sig: pytorch.manifest
> 	$(GRAPHENEDIR)/Pal/src/host/Linux-SGX/signer/pal-sgx-sign -libpal $(GRAPHENEDIR)/Runtime/libpal-Linux-SGX.so -key $(GRAPHENEDIR)/Pal/src/host/Linux-SGX/signer/enclave-key.pem -output pytorch.manifest.sgx -exec /usr/bin/python3 -manifest $<
> ```

Hard to read. Could you please split into multiple lines.
___
*[pytorch/Makefile, line 45 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/66#-LzIpLSXCa7h3fFI3DvQ:-LzIpLSXCa7h3fFI3DvR:bvutbzy) ([raw file](https://github.com/oscarlab/graphene-tests/blob/e2562c76d3135a4ea4e0165987cee7320a482b0a/pytorch/Makefile#L45)):*
> ```Makefile
> 
> python3.sig: python3.manifest
> 	$(GRAPHENEDIR)/Pal/src/host/Linux-SGX/signer/pal-sgx-sign -libpal $(GRAPHENEDIR)/Runtime/libpal-Linux-SGX.so -key $(GRAPHENEDIR)/Pal/src/host/Linux-SGX/signer/enclave-key.pem -output python3.manifest.sgx -exec /usr/bin/python3 -manifest $<
> ```

Hard to read. Could you please split into multiple lines.
___
*[pytorch/pytorch.manifest.template, line 103 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/66#-LzIpjcw1TjOc5t_xrY-:-LzIpjcw1TjOc5t_xrY0:b-bomorv) ([raw file](https://github.com/oscarlab/graphene-tests/blob/e2562c76d3135a4ea4e0165987cee7320a482b0a/pytorch/pytorch.manifest.template#L103)):*
> ```
> # Ubuntu16 sgx.trusted_files.libssl    = file:/lib/x86_64-linux-gnu/libssl.so.1.0.0
> # Ubuntu18 sgx.trusted_files.libcrypto = file:/usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
> # Ubuntu18 sgx.trusted_files.libssl    = file:/usr/lib/x86_64-linux-gnu/libssl.so.1.1
> ```

Again, this is smart. We should standardize this among ourselves (e.g., I'd prefer more special symbols around Ubuntu, something like `[Ubuntu16] sgx....`)
___
*[pytorch/README.md, line 3 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/66#-LzIq9Mj7MKuRsg6Ut5D:-LzIq9Mj7MKuRsg6Ut5E:b-pihra8) ([raw file](https://github.com/oscarlab/graphene-tests/blob/e2562c76d3135a4ea4e0165987cee7320a482b0a/pytorch/README.md#L3)):*
> ```Markdown
> # PyTorch
> 
> This directory contains steps and artifacts to run a PyTorch sample workload on Graphene. Specifically, this example uses a pre-trained model for image classification. We tested this on Ubuntu 16.04 and 18.04. The sample uses the package versions of Python (3.5 and 3.6) coming with each distribution.
> ```

This whole file does not observe the 100-char-limit. Please reformat with multiple lines.

**Review by yamahata — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/66)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @thomasknauth)

___
*[pytorch/Makefile, line 9 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/66#-LzJ8dbxBai405AJJg27:-LzJ8dby6xJyPTJy6iZP:budfwfd) ([raw file](https://github.com/oscarlab/graphene-tests/blob/e2562c76d3135a4ea4e0165987cee7320a482b0a/pytorch/Makefile#L9)):*
> ```
> shell grep _ID /etc/lsb-release
> ```

Per LSB(Linux Standard Base), please use "lsb_release --short --id" .
(lsb_release command)
___
*[pytorch/Makefile, line 10 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/66#-LzJ8tUJAFrIobdb57vf:-LzJ8tUJAFrIobdb57vg:b-iae5b) ([raw file](https://github.com/oscarlab/graphene-tests/blob/e2562c76d3135a4ea4e0165987cee7320a482b0a/pytorch/Makefile#L10)):*
> ```Makefile
> 
> DISTRIB_ID ?= $(shell grep _ID /etc/lsb-release | cut -d= -f2)
> DISTRIB_RLEASE_MAJOR ?= $(shell grep _RELEASE /etc/lsb-release | cut -d= -f 2 | cut -d. -f 1)
> ```

lsb_release --short --release

**Review by thomasknauth — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/66)* status: 3 of 6 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @thomasknauth, and @yamahata)

___
*[pytorch/Makefile, line 9 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/66#-LzJ8dbxBai405AJJg27:-LzJKKIF-mvF5Cq3Aur7:b-4izl8r) ([raw file](https://github.com/oscarlab/graphene-tests/blob/e2562c76d3135a4ea4e0165987cee7320a482b0a/pytorch/Makefile#L9)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

> ```
> shell grep _ID /etc/lsb-release
> ```

Per LSB(Linux Standard Base), please use "lsb_release --short --id" .
(lsb_release command)
</blockquote></details>

True, but this requires the lsb_release package installed, whereas the grep/cut acrobatics does not. For example, a stock Ubuntu 16/18 Docker container does not have this installed by default (for whatever reason). I've changed it according to your suggestion.
___
*[pytorch/Makefile, line 10 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/66#-LzJ8tUJAFrIobdb57vf:-LzJLzF97C53IK-of2A6:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/e2562c76d3135a4ea4e0165987cee7320a482b0a/pytorch/Makefile#L10)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

lsb_release --short --release
</blockquote></details>

Done.
___
*[pytorch/Makefile, line 33 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/66#-LzIpCb34VIRmB5K1TO1:-LzJMwFa1McMFsfDZPAZ:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/e2562c76d3135a4ea4e0165987cee7320a482b0a/pytorch/Makefile#L33)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Hard to read. Could you please split into multiple lines.
</blockquote></details>

Done.
___
*[pytorch/Makefile, line 45 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/66#-LzIpLSXCa7h3fFI3DvQ:-LzJMwff-qby8Oe7Nz5U:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/e2562c76d3135a4ea4e0165987cee7320a482b0a/pytorch/Makefile#L45)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Hard to read. Could you please split into multiple lines.
</blockquote></details>

Done.
___
*[pytorch/README.md, line 3 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/66#-LzIq9Mj7MKuRsg6Ut5D:-LzJNASJ0NbEIAIHhwQH:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/e2562c76d3135a4ea4e0165987cee7320a482b0a/pytorch/README.md#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This whole file does not observe the 100-char-limit. Please reformat with multiple lines.
</blockquote></details>

Done.

**Review by yamahata — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/66)* status: 3 of 6 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @thomasknauth)

___
*[pytorch/Makefile, line 9 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/66#-LzJ8dbxBai405AJJg27:-LzJTdYi9YizTL81v5XM:bpeggfu) ([raw file](https://github.com/oscarlab/graphene-tests/blob/e2562c76d3135a4ea4e0165987cee7320a482b0a/pytorch/Makefile#L9)):*
<details><summary><i>Previously, thomasknauth (Thomas Knauth) wrote…</i></summary><blockquote>

True, but this requires the lsb_release package installed, whereas the grep/cut acrobatics does not. For example, a stock Ubuntu 16/18 Docker container does not have this installed by default (for whatever reason). I've changed it according to your suggestion.
</blockquote></details>

Ah, then I'll scratch that. Please feel free to revert it.

**Review by yamahata — COMMENTED** [review]
> Reviewed 3 of 6 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/66)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @thomasknauth)

**Review by dimakuv — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/66)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @thomasknauth)

**Review by yamahata — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/66)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/66)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @thomasknauth)

___
*[pytorch/Makefile, line 1 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/66#-LzTLfsi1URuonVxFWJw:-LzTLfsi1URuonVxFWJx:b-vj1lce) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d7ab32dafd5859640b3521d0641d9d6a25f2e6ee/pytorch/Makefile#L1)):*
> ```Makefile
> GRAPHENEDIR?=../../../../..
> ```

Please add spaces around `?=`
___
*[pytorch/pytorchexample.py, line 23 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/66#-LzTKxYMDYHgA-ijQb2g:-LzTKxYMDYHgA-ijQb2h:b-z2r3p5) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d7ab32dafd5859640b3521d0641d9d6a25f2e6ee/pytorch/pytorchexample.py#L23)):*
> ```Python
> 
> # Load the image.
> from PIL import Image
> ```

This dependency seems to be missing from the README (AFAIR this will be `pillow` package from `pip`)
___
*[pytorch/README.md, line 9 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/66#-LzTJUlyBWysva_yXKQp:-LzTJUlyBWysva_yXKQq:bymsxap) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d7ab32dafd5859640b3521d0641d9d6a25f2e6ee/pytorch/README.md#L9)):*
> ```Markdown
> 
> The workload reads an image from a file on disk `input.jpg` and runs the classifier to detect what
> object is present in the image. For the image shipping with the workload, the output will be
> ```

`shipping` -> `shipped`
`will be` -> `should be:`
___
*[pytorch/README.md, line 23 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/66#-LzTJup7997IhUipzDIF:-LzTJup7997IhUipzDIG:bl9cthh) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d7ab32dafd5859640b3521d0641d9d6a25f2e6ee/pytorch/README.md#L23)):*
> ```Markdown
> 
> - `sudo apt-get install python3-pip lsb-release` to install `pip` and `lsb_release`. The former is required to install
>   addition Python packages while the latter is used by the Makefile.
> ```

Please fix the wrapping here.
___
*[pytorch/README.md, line 23 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/66#-LzTK0y53H1V0OjFmakW:-LzTK0y53H1V0OjFmakX:be8cdm9) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d7ab32dafd5859640b3521d0641d9d6a25f2e6ee/pytorch/README.md#L23)):*
> ```Markdown
> 
> - `sudo apt-get install python3-pip lsb-release` to install `pip` and `lsb_release`. The former is required to install
>   addition Python packages while the latter is used by the Makefile.
> ```

`addition` -> `additional`

**Review by thomasknauth — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/66)* status: 4 of 6 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @yamahata)

___
*[pytorch/Makefile, line 1 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/66#-LzTLfsi1URuonVxFWJw:-LzwkQzC7I1j0POqCftY:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d7ab32dafd5859640b3521d0641d9d6a25f2e6ee/pytorch/Makefile#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please add spaces around `?=`
</blockquote></details>

Done.
___
*[pytorch/pytorchexample.py, line 23 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/66#-LzTKxYMDYHgA-ijQb2g:-Lzwkawo1LQZE084IBL0:b-urquo) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d7ab32dafd5859640b3521d0641d9d6a25f2e6ee/pytorch/pytorchexample.py#L23)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This dependency seems to be missing from the README (AFAIR this will be `pillow` package from `pip`)
</blockquote></details>

This is pulled as part of pytorch. I never had to install it independently.
___
*[pytorch/README.md, line 9 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/66#-LzTJUlyBWysva_yXKQp:-LzwlGM56QDTxaQg7RBY:b5no96x) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d7ab32dafd5859640b3521d0641d9d6a25f2e6ee/pytorch/README.md#L9)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`shipping` -> `shipped`
`will be` -> `should be:`
</blockquote></details>

"shipping" is fine here
___
*[pytorch/README.md, line 23 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/66#-LzTK0y53H1V0OjFmakW:-LzwmP4o84tTll7pv-3y:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d7ab32dafd5859640b3521d0641d9d6a25f2e6ee/pytorch/README.md#L23)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`addition` -> `additional`
</blockquote></details>

Done.
___
*[pytorch/README.md, line 23 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/66#-LzTJup7997IhUipzDIF:-LzwmPWc1PLVJeNEZrc8:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d7ab32dafd5859640b3521d0641d9d6a25f2e6ee/pytorch/README.md#L23)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please fix the wrapping here.
</blockquote></details>

Done.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/66)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @thomasknauth)

___
*[pytorch/pytorchexample.py, line 23 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/66#-LzTKxYMDYHgA-ijQb2g:-LzxGnlJ2Wp8iHej06hS:bn7fint) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d7ab32dafd5859640b3521d0641d9d6a25f2e6ee/pytorch/pytorchexample.py#L23)):*
<details><summary><i>Previously, thomasknauth (Thomas Knauth) wrote…</i></summary><blockquote>

This is pulled as part of pytorch. I never had to install it independently.
</blockquote></details>

I'd prefer to add it explicitly instead of relying on PyTorch to have this in dependencies. This may change in the future and break our setup instructions.

**Review by thomasknauth — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/66)* status: 5 of 6 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[pytorch/pytorchexample.py, line 23 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/66#-LzTKxYMDYHgA-ijQb2g:-M-MGZlT2cdcRCj2_IDc:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d7ab32dafd5859640b3521d0641d9d6a25f2e6ee/pytorch/pytorchexample.py#L23)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd prefer to add it explicitly instead of relying on PyTorch to have this in dependencies. This may change in the future and break our setup instructions.
</blockquote></details>

Done.

**Review by dimakuv — COMMENTED** [review]
I am taking over this PR. @mkow Could you have another look at this PR? Would be good to continue with fixes and the merging process.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/66#-:-M1EQE_lDq1ONjhr6-9h:b-4edyoo)* status: 5 of 6 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/66)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Review by dimakuv — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/66)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by dimakuv — DISMISSED** [review]
> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/66)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

**Review by dimakuv — DISMISSED** [review]
> Reviewed 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/66)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

**Review by mkow — DISMISSED** [review]
> Reviewed 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/66)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/66)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/66)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
