### PR TITLE
Add LTP repository as a submodule

### PR DESCRIPTION
**Pull request by chiache**
Updating the LTP version to the latest stable release (20190517).

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/6)

### CODE REVIEW

**Review by yamahata — DISMISSED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/6)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required) (waiting on @donporter and @mkow)

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/6)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @chiache, @donporter, and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/6#-LjxMabm5TsnvHgDHFXx:-LjxMabm5TsnvHgDHFXy:b23gqma) (no related file):*
Shouldn't we also update BLOCKED, PASSED, and others as part of this PR? Surely some tests broke or were added.

---

**Review by donporter — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/6)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/6#-LjxMabm5TsnvHgDHFXx:-LjxNick6e3qmeRzZD8S:bcrf842) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Shouldn't we also update BLOCKED, PASSED, and others as part of this PR? Surely some tests broke or were added.
</blockquote></details>

Agreed with @dimakuv.  If there are any regressions, I might start by using the commit that is equal to the release we have been using, and update it more incrementally.   I would rather not dump a lot of useful tests.

---

**Review by chiache — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/6)* status: 3 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/6#-LjxMabm5TsnvHgDHFXx:-Lk02qG71DA0BIhN_e35:b-896fix) (no related file):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

Agreed with @dimakuv.  If there are any regressions, I might start by using the commit that is equal to the release we have been using, and update it more incrementally.   I would rather not dump a lot of useful tests.
</blockquote></details>

Done.

---

**Review by dimakuv — DISMISSED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/6)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required) (waiting on @mkow)

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/6)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @chiache and @mkow)

___
*[ltp/Makefile, line 14 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/6#-Lk0YJ6Z-dyaATqOpISB:-Lk0YJ6Z-dyaATqOpISC:b-43ddfw) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d981c9d9e0d0792fb9950f4b07413ab5f9ea389b/ltp/Makefile#L14)):*
> ```Makefile
> 
> $(SRCDIR)/configure:
> 	git submodule update --init $(SRCDIR)
> ```

This is horribly wrong. One should never run VCS commands from build scripts  for multiple reasons, some of the most obvious being:

1. You may not be in git, because source was unpacked from tarball prepared by distro maintainer. Virtually every package works that way.
2. You may not have access to the Internet, because source was downloaded earlier and only then unpacked (see 1.).
(WRT to this point, this is actually no worse than `wget`, which was here earlier).
3. Some testing and CI(-oriented) tools need to be able to check out a particular commit/ref and expect it not changed for the duration of build. Exhibit A: `git blame`.

The proper way is to use `--recursive` in top-level `git submodule update`.

**Review by chiache — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/6)* status: 4 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @mkow, @woju, and @yamahata)

___
*[ltp/Makefile, line 14 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/6#-Lk0YJ6Z-dyaATqOpISB:-Lk0bQq64qeRuGjQXhRA:b-u6zmsu) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d981c9d9e0d0792fb9950f4b07413ab5f9ea389b/ltp/Makefile#L14)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This is horribly wrong. One should never run VCS commands from build scripts  for multiple reasons, some of the most obvious being:

1. You may not be in git, because source was unpacked from tarball prepared by distro maintainer. Virtually every package works that way.
2. You may not have access to the Internet, because source was downloaded earlier and only then unpacked (see 1.).
(WRT to this point, this is actually no worse than `wget`, which was here earlier).
3. Some testing and CI(-oriented) tools need to be able to check out a particular commit/ref and expect it not changed for the duration of build. Exhibit A: `git blame`.

The proper way is to use `--recursive` in top-level `git submodule update`.
</blockquote></details>

Fair enough. I put a warning here if the `src` directory is empty, to instruct the user to update the submodule or download the source code directly.

I think we are trying to separate the `graphene-tests` submodule from other submodules to reduce cloning time.

**Comment by woju** [comment]
___
*[ltp/Makefile, line 14 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/6#-Lk0YJ6Z-dyaATqOpISB:-Lk0huCE9xeNbU4zh5J9:b-d5395a) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d981c9d9e0d0792fb9950f4b07413ab5f9ea389b/ltp/Makefile#L14)):*
<details><summary><i>Previously, chiache (Chia-Che Tsai) wrote…</i></summary><blockquote>

Fair enough. I put a warning here if the `src` directory is empty, to instruct the user to update the submodule or download the source code directly.

I think we are trying to separate the `graphene-tests` submodule from other submodules to reduce cloning time.
</blockquote></details>

Sure, a warning might be OK. And I agree with the aim.

But the thing to be fixed should be README in (IIUC) `graphene`, which says `git submodule update --init ...` without recursive.

Thanks.

**Review by donporter — DISMISSED** [review]
> Reviewed 2 of 3 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/6)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @mkow)

**Review by donporter — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/6)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @mkow)

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/6)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
