### PR TITLE
Fix make clean

### PR DESCRIPTION
**Pull request by HW42**
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/31)

### CODE REVIEW

**Review by yamahata — COMMENTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/31)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by donporter — DISMISSED** [review]
> Reviewed 6 of 6 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/31)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by dimakuv — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/31)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by yamahata — DISMISSED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/31)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — DISMISSED** [review]
> Reviewed 6 of 6 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/31)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> Reviewed 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/31)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/31)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
