### PR TITLE
Fix the Makefile to leverage the GRAPHENE variable to locate GRAPHENE…

### PR DESCRIPTION
**Pull request by AI-Memory**
This PR makes the GSGX Tensorflows to be capable to build and run outside of Graphene project.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/51)

### CODE REVIEW

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/51)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/51)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by yamahata — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/51)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/51)* status: 0 of 16 files reviewed, all discussions resolved (waiting on @dimakuv, @mkow, and @yamahata)

**Pull request closed without merging**
