### PR TITLE
Rewrite Curl example

### PR DESCRIPTION
**Pull request by dimakuv**
Simple PR rewriting the Curl example. The corresponding PR in the main repo also adds Curl test to Jenkins.

The corresponding PR is https://github.com/oscarlab/graphene/pull/1178.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/56)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/56)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[curl/curl.manifest.template, line 52 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/56#-LujK3lO7Suu7-oEuSdh:-LujK3lO7Suu7-oEuSdi:bew0v5h) ([raw file](https://github.com/oscarlab/graphene-tests/blob/e37c5cf9015d4d8d486991cf6cfdfc8746c17beb/curl/curl.manifest.template#L52)):*
> ```
> sgx.thread_num = 4
> 
> # Specify all libraries used by Memcached and its dependencies (including all
> ```

Now I know where you copied it from!
___
*[curl/Makefile, line 30 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/56#-LujH-nE6pSp5M_8z0Mj:-LujH-nE6pSp5M_8z0Mk:b-x278oy) ([raw file](https://github.com/oscarlab/graphene-tests/blob/e37c5cf9015d4d8d486991cf6cfdfc8746c17beb/curl/Makefile#L30)):*
> ```Makefile
> 
> # curl dependencies (generated from ldd). For SGX, the manifest needs to list all the libraries
> # loaded during execution, so that the signer can include the file checksums.
> ```

`checksums` -> `hashes`
___
*[curl/README.md, line 3 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/56#-LujH_ja6rksEJ2HgN4f:-LujH_ja6rksEJ2HgN4g:b-kn8o1p) ([raw file](https://github.com/oscarlab/graphene-tests/blob/e37c5cf9015d4d8d486991cf6cfdfc8746c17beb/curl/README.md#L3)):*
> ```Markdown
> # Curl
> 
> This directory contains a Makefile and template manifest to run curl on Graphene. We tested with
> ```

`tested` -> `tested it`
___
*[curl/README.md, line 11 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/56#-LujHj6cDnBX0LDiG_Tj:-LujHj6cDnBX0LDiG_Tk:b-z5cnjg) ([raw file](https://github.com/oscarlab/graphene-tests/blob/e37c5cf9015d4d8d486991cf6cfdfc8746c17beb/curl/README.md#L11)):*
> ```Markdown
> # Quick Start
> 
> To run the regression test execute ```make check```. To do the same for SGX, execute ```SGX=1 make
> ```

I'd prefer `make SGX=1 check`, this form is more common in our documentation.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/56)* status: 4 of 7 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[curl/curl.manifest.template, line 52 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/56#-LujK3lO7Suu7-oEuSdh:-LumFKyy5bGEWq73SOWu:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/e37c5cf9015d4d8d486991cf6cfdfc8746c17beb/curl/curl.manifest.template#L52)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Now I know where you copied it from!
</blockquote></details>

Done.
___
*[curl/Makefile, line 30 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/56#-LujH-nE6pSp5M_8z0Mj:-LumFdaiCwnvypIaI17q:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/e37c5cf9015d4d8d486991cf6cfdfc8746c17beb/curl/Makefile#L30)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`checksums` -> `hashes`
</blockquote></details>

Done.
___
*[curl/README.md, line 3 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/56#-LujH_ja6rksEJ2HgN4f:-LumFjjP3j-jE5DJSD0u:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/e37c5cf9015d4d8d486991cf6cfdfc8746c17beb/curl/README.md#L3)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`tested` -> `tested it`
</blockquote></details>

Done.
___
*[curl/README.md, line 11 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/56#-LujHj6cDnBX0LDiG_Tj:-LumFq4d7il1vPjBzvY9:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/e37c5cf9015d4d8d486991cf6cfdfc8746c17beb/curl/README.md#L11)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd prefer `make SGX=1 check`, this form is more common in our documentation.
</blockquote></details>

Done.

**Review by mkow — DISMISSED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/56)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/56)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by yamahata — APPROVED** [review]
> Reviewed 4 of 7 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/56)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
