### PR TITLE
Update gitignore

### PR DESCRIPTION
**Pull request by HW42**
Matching PR: https://github.com/oscarlab/graphene/pull/1287.

This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/69)

### CODE REVIEW

**Review by mkow — DISMISSED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/69)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by yamahata — DISMISSED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/69)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dimakuv — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/69)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by dimakuv** [comment]
@HW42 Does it have a corresponding PR in main repo?

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/69)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/69)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
