### PR TITLE
Rewrite Nginx example

### PR DESCRIPTION
**Pull request by dimakuv**
Rewriting the Nginx example.

Requires https://github.com/oscarlab/graphene/pull/1019 for correct work.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/42)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 55 of 55 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/42)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[nginx/benchmark-http.sh, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/42#-LpsJhTT-y4AVOsxrq27:-LpsJhTU1YnNV1JVZ5t0:bgubbpg) ([raw file](https://github.com/oscarlab/graphene-tests/blob/f3446de691c9cc8a253e00fc420d216880896aa7/nginx/benchmark-http.sh#L1)):*
> ```Shell
> ../lighttpd/benchmark-http.sh
> ```

Could we move such scripts to a separate directory? To something like "common_tools".
Otherwise this dependency is quite unexpected and people changing the script probably won't even think that it can be used by other apps.
___
*[nginx/Makefile, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/42#-LpsLey22uVlqkllyLZf:-LpsLey22uVlqkllyLZg:b-8ghrko) ([raw file](https://github.com/oscarlab/graphene-tests/blob/f3446de691c9cc8a253e00fc420d216880896aa7/nginx/Makefile#L1)):*
> ```Makefile
> # Build the manifest for Nginx:
> ```

`Build` -> `Building`
___
*[nginx/Makefile, line 14 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/42#-LpsLryp6gMFUzeuAkbY:-LpsLryp6gMFUzeuAkbZ:bp71q74) ([raw file](https://github.com/oscarlab/graphene-tests/blob/f3446de691c9cc8a253e00fc420d216880896aa7/nginx/Makefile#L14)):*
> ```Makefile
> 
> THIS_DIR := $(dir $(lastword $(MAKEFILE_LIST)))
> ifeq ($(THIS_DIR), ./)   # to workaround the Graphene bug with allowed_files' paths
> ```

Do we have any ticket for this? Could you link it here?
___
*[nginx/Makefile, line 22 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/42#-LpsM1T80BQRyHD4gxyt:-LpsM1T80BQRyHD4gxyu:b-gsxio8) ([raw file](https://github.com/oscarlab/graphene-tests/blob/f3446de691c9cc8a253e00fc420d216880896aa7/nginx/Makefile#L22)):*
> ```Makefile
> NGINX_CHECKSUM ?= f11c2a6dd1d3515736f0324857957db2de98be862461b5a542a3ac6188dbe32b
> 
> # Mirros for downloading the Nginx source code
> ```

`Mirros` -> `Mirrors`
___
*[nginx/nginx.manifest.template, line 74 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/42#-LpsQ6k_9XA1feKRoepd:-LpsQ6k_9XA1feKRoepe:b-rj0kal) ([raw file](https://github.com/oscarlab/graphene-tests/blob/f3446de691c9cc8a253e00fc420d216880896aa7/nginx/nginx.manifest.template#L74)):*
> ```
> # Name Service Switch (NSS) libraries (Glibc dependencies)
> sgx.trusted_files.libnsscompat = file:/lib/x86_64-linux-gnu/libnss_compat.so.2
> sgx.trusted_files.libnssfiles  = file:/lib/x86_64-linux-gnu/libnss_files.so.2
> ```

double space?
___
*[nginx/nginx.manifest.template, line 75 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/42#-LpsQ2CX-l_V6uqg36L-:-LpsQ2CX-l_V6uqg36L0:b-rj0kal) ([raw file](https://github.com/oscarlab/graphene-tests/blob/f3446de691c9cc8a253e00fc420d216880896aa7/nginx/nginx.manifest.template#L75)):*
> ```
> sgx.trusted_files.libnsscompat = file:/lib/x86_64-linux-gnu/libnss_compat.so.2
> sgx.trusted_files.libnssfiles  = file:/lib/x86_64-linux-gnu/libnss_files.so.2
> sgx.trusted_files.libnssnis  = file:/lib/x86_64-linux-gnu/libnss_nis.so.2
> ```

double space?

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/42)* status: 53 of 55 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @mkow)

___
*[nginx/benchmark-http.sh, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/42#-LpsJhTT-y4AVOsxrq27:-Lq-SyRa7H2_rAd9RbgE:b-hbaub) ([raw file](https://github.com/oscarlab/graphene-tests/blob/f3446de691c9cc8a253e00fc420d216880896aa7/nginx/benchmark-http.sh#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could we move such scripts to a separate directory? To something like "common_tools".
Otherwise this dependency is quite unexpected and people changing the script probably won't even think that it can be used by other apps.
</blockquote></details>

Will do in a separate PR.
___
*[nginx/Makefile, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/42#-LpsLey22uVlqkllyLZf:-Lq-PJlw6CxS2CwVCWhh:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/f3446de691c9cc8a253e00fc420d216880896aa7/nginx/Makefile#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`Build` -> `Building`
</blockquote></details>

Done.
___
*[nginx/Makefile, line 14 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/42#-LpsLryp6gMFUzeuAkbY:-Lq-S9_V5PoI-9nl93jL:bb6un1j) ([raw file](https://github.com/oscarlab/graphene-tests/blob/f3446de691c9cc8a253e00fc420d216880896aa7/nginx/Makefile#L14)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Do we have any ticket for this? Could you link it here?
</blockquote></details>

Done
___
*[nginx/Makefile, line 22 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/42#-LpsM1T80BQRyHD4gxyt:-Lq-SDaXAVmhrG0g9axw:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/f3446de691c9cc8a253e00fc420d216880896aa7/nginx/Makefile#L22)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`Mirros` -> `Mirrors`
</blockquote></details>

Done.
___
*[nginx/nginx.manifest.template, line 74 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/42#-LpsQ6k_9XA1feKRoepd:-Lq-SHwA1dtlFlJ3_rz3:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/f3446de691c9cc8a253e00fc420d216880896aa7/nginx/nginx.manifest.template#L74)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

double space?
</blockquote></details>

Done.
___
*[nginx/nginx.manifest.template, line 75 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/42#-LpsQ2CX-l_V6uqg36L-:-Lq-SIKnAd0r0KrOQa-5:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/f3446de691c9cc8a253e00fc420d216880896aa7/nginx/nginx.manifest.template#L75)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

double space?
</blockquote></details>

Done.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/42)* status: 53 of 55 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[nginx/benchmark-http.sh, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/42#-LpsJhTT-y4AVOsxrq27:-Lq-V5ZN04uoFVUYfQbu:bb0hvyc) ([raw file](https://github.com/oscarlab/graphene-tests/blob/f3446de691c9cc8a253e00fc420d216880896aa7/nginx/benchmark-http.sh#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Will do in a separate PR.
</blockquote></details>

Done. See https://github.com/oscarlab/graphene-tests/pull/43.

**Review by mkow — DISMISSED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/42)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by yamahata — APPROVED** [review]
> Reviewed 53 of 55 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/42)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/42)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
